export const config = {
	DEFAULT_UNKNOWN_USER_ID: "unknown",
	ERROR: {
		PERSON: {
			NOT_FOUND: "Person not found",
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update person",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
			GETTING_ALL_USERS: "Getting all persons",
		},
		USER: {
			NOT_FOUND: "User not found",
			INVALID_ID: "Invalid user ID",
			MISSING_ID: "Missing user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update user",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
			INVALID_USER_ID_FORMAT: "Invalid user ID format",
			INVALID_FIELDS_PARAMETER: "Invalid fields parameter",
			INVALID_QUERY_PARAMETERS: "Invalid query parameters",
			INVALID_UPDATE_DATA: "Invalid update data",
			REQUEST_BODY_EMPTY: "Request body cannot be empty",
			VALIDATION_FAILED: "Validation failed",
			FIRST_NAME_REQUIRED: "First name is required",
			LAST_NAME_REQUIRED: "Last name is required",
			UNAUTHORIZED_USER_ID_NOT_FOUND: "Unauthorized - User ID not found",
			ERROR_DURING_USER_CREATION: "Error during user creation",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
			UPLOADING_AVATAR: "Uploading avatar for user",
			AVATAR_UPLOADED: "Avatar uploaded successfully",
			ORGANIZATION_VERIFIED: "Organization verified",
			USER_ALREADY_EXISTS: "User already exists",

			INVALID_ID_FORMAT: "Invalid user ID format",

			CREATE_FAILED: "Error creating user",

			DELETE_FAILED: "Error deleting user",
			GET_FAILED: "Error getting user",
			GET_ALL_FAILED: "Error getting users",
			ERROR_GETTING: "Error getting user",
			ERROR_UPDATING: "Error updating user",
		},
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			INVALID_ID: "Invalid ID",
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			SUPPLIER_ID: "Require Supplier Id or Source Id",
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		ROLE: {
			VALIDATION_FAILED: "Role validation failed",
			INVALID_ID_FORMAT: "Invalid role ID format",
			NOT_FOUND: "Role not found",
			CREATE_FAILED: "Error creating role",
			UPDATE_FAILED: "Error updating role",
			DELETE_FAILED: "Error deleting role",
			GET_FAILED: "Error getting role",
			GET_ALL_FAILED: "Error getting roles",
			ERROR_GETTING: "Error getting role",
			ERROR_UPDATING: "Error updating role",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},

		PRODUCT: {
			VALIDATION_FAILED: "Product validation failed",
			INVALID_ID_FORMAT: "Invalid product ID format",
			NOT_FOUND: "Product not found",
			CREATE_FAILED: "Error creating product",
			UPDATE_FAILED: "Error updating product",
			DELETE_FAILED: "Error deleting product",
			GET_FAILED: "Error getting product",
			GET_ALL_FAILED: "Error getting products",
			ERROR_GETTING: "Error getting product",
			ERROR_UPDATING: "Error updating product",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		BATCH: {
			VALIDATION_FAILED: "Batch validation failed",
			INVALID_ID_FORMAT: "Invalid batch ID format",
			NOT_FOUND: "Batch not found",
			CREATE_FAILED: "Error creating batch",
			UPDATE_FAILED: "Error updating batch",
			DELETE_FAILED: "Error deleting batch",
			GET_FAILED: "Error getting batch",
			GET_ALL_FAILED: "Error getting batchs",
			ERROR_GETTING: "Error getting batch",
			ERROR_UPDATING: "Error updating batch",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		STOCK: {
			VALIDATION_FAILED: "Stock validation failed",
			INVALID_ID_FORMAT: "Invalid stock ID format",
			NOT_FOUND: "Stock not found",
			CREATE_FAILED: "Error creating stock",
			UPDATE_FAILED: "Error updating stock",
			DELETE_FAILED: "Error deleting stock",
			GET_FAILED: "Error getting stock",
			GET_ALL_FAILED: "Error getting stocks",
			ERROR_GETTING: "Error getting stock",
			ERROR_UPDATING: "Error updating stock",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SUPPLIER: {
			VALIDATION_FAILED: "Supplier validation failed",
			INVALID_ID_FORMAT: "Invalid supplier ID format",
			NOT_FOUND: "Supplier not found",
			CREATE_FAILED: "Error creating supplier",
			UPDATE_FAILED: "Error updating supplier",
			DELETE_FAILED: "Error deleting supplier",
			GET_FAILED: "Error getting supplier",
			GET_ALL_FAILED: "Error getting suppliers",
			ERROR_GETTING: "Error getting supplier",
			ERROR_UPDATING: "Error updating supplier",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		PURCHASEORDERITEM: {
			VALIDATION_FAILED: "PurchaseOrderItem validation failed",
			INVALID_ID_FORMAT: "Invalid purchaseorderitem ID format",
			NOT_FOUND: "PurchaseOrderItem not found",
			CREATE_FAILED: "Error creating purchaseorderitem",
			UPDATE_FAILED: "Error updating purchaseorderitem",
			DELETE_FAILED: "Error deleting purchaseorderitem",
			GET_FAILED: "Error getting purchaseorderitem",
			GET_ALL_FAILED: "Error getting purchaseorderitems",
			ERROR_GETTING: "Error getting purchaseorderitem",
			ERROR_UPDATING: "Error updating purchaseorderitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		TRANSACTION: {
			VALIDATION_FAILED: "Transaction validation failed",
			INVALID_ID_FORMAT: "Invalid transaction ID format",
			NOT_FOUND: "Transaction not found",
			CREATE_FAILED: "Error creating transaction",
			UPDATE_FAILED: "Error updating transaction",
			DELETE_FAILED: "Error deleting transaction",
			GET_FAILED: "Error getting transaction",
			GET_ALL_FAILED: "Error getting transactions",
			ERROR_GETTING: "Error getting transaction",
			ERROR_UPDATING: "Error updating transaction",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		LOCATION: {
			VALIDATION_FAILED: "Location validation failed",
			INVALID_ID_FORMAT: "Invalid location ID format",
			NOT_FOUND: "Location not found",
			CREATE_FAILED: "Error creating location",
			UPDATE_FAILED: "Error updating location",
			DELETE_FAILED: "Error deleting location",
			GET_FAILED: "Error getting location",
			GET_ALL_FAILED: "Error getting locations",
			ERROR_GETTING: "Error getting location",
			ERROR_UPDATING: "Error updating location",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		TRANSACTIONITEM: {
			VALIDATION_FAILED: "TransactionItem validation failed",
			INVALID_ID_FORMAT: "Invalid transactionitem ID format",
			NOT_FOUND: "TransactionItem not found",
			CREATE_FAILED: "Error creating transactionitem",
			UPDATE_FAILED: "Error updating transactionitem",
			DELETE_FAILED: "Error deleting transactionitem",
			GET_FAILED: "Error getting transactionitem",
			GET_ALL_FAILED: "Error getting transactionitems",
			ERROR_GETTING: "Error getting transactionitem",
			ERROR_UPDATING: "Error updating transactionitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		STOCKRECORD: {
			NOT_FOUND: "Stock record not found",
			CREATE_FAILED: "Failed to create stock record",
			GET_ALL_FAILED: "Failed to retrieve stock records",
			ERROR_GETTING: "Error retrieving stock record",
			ERROR_UPDATING: "Error updating stock record",
			DELETE_FAILED: "Failed to delete stock record",
		},
		DELIVERORDER: {
			VALIDATION_FAILED: "DeliverOrder validation failed",
			INVALID_ID_FORMAT: "Invalid deliverorder ID format",
			NOT_FOUND: "DeliverOrder not found",
			CREATE_FAILED: "Error creating deliverorder",
			UPDATE_FAILED: "Error updating deliverorder",
			DELETE_FAILED: "Error deleting deliverorder",
			GET_FAILED: "Error getting deliverorder",
			GET_ALL_FAILED: "Error getting deliverorders",
			ERROR_GETTING: "Error getting deliverorder",
			ERROR_UPDATING: "Error updating deliverorder",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		ORGANIZATION: {
			VALIDATION_FAILED: "Organization validation failed",
			INVALID_ID_FORMAT: "Invalid organization ID format",
			NOT_FOUND: "Organization not found",
			CREATE_FAILED: "Error creating organization",
			UPDATE_FAILED: "Error updating organization",
			DELETE_FAILED: "Error deleting organization",
			GET_FAILED: "Error getting organization",
			GET_ALL_FAILED: "Error getting organizations",
			ERROR_GETTING: "Error getting organization",
			ERROR_UPDATING: "Error updating organization",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYRECEIPT: {
			VALIDATION_FAILED: "DeliveryReceipt validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryreceipt ID format",
			NOT_FOUND: "DeliveryReceipt not found",
			CREATE_FAILED: "Error creating deliveryreceipt",
			UPDATE_FAILED: "Error updating deliveryreceipt",
			DELETE_FAILED: "Error deleting deliveryreceipt",
			GET_FAILED: "Error getting deliveryreceipt",
			GET_ALL_FAILED: "Error getting deliveryreceipts",
			ERROR_GETTING: "Error getting deliveryreceipt",
			ERROR_UPDATING: "Error updating deliveryreceipt",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYREQUEST: {
			VALIDATION_FAILED: "DeliveryRequest validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryrequest ID format",
			NOT_FOUND: "DeliveryRequest not found",
			CREATE_FAILED: "Error creating deliveryrequest",
			UPDATE_FAILED: "Error updating deliveryrequest",
			DELETE_FAILED: "Error deleting deliveryrequest",
			GET_FAILED: "Error getting deliveryrequest",
			GET_ALL_FAILED: "Error getting deliveryrequests",
			ERROR_GETTING: "Error getting deliveryrequest",
			ERROR_UPDATING: "Error updating deliveryrequest",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYREQUESTITEM: {
			VALIDATION_FAILED: "DeliveryRequestItem validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryrequestitem ID format",
			NOT_FOUND: "DeliveryRequestItem not found",
			CREATE_FAILED: "Error creating deliveryrequestitem",
			UPDATE_FAILED: "Error updating deliveryrequestitem",
			DELETE_FAILED: "Error deleting deliveryrequestitem",
			GET_FAILED: "Error getting deliveryrequestitem",
			GET_ALL_FAILED: "Error getting deliveryrequestitems",
			ERROR_GETTING: "Error getting deliveryrequestitem",
			ERROR_UPDATING: "Error updating deliveryrequestitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYRECEIPTITEM: {
			VALIDATION_FAILED: "DeliveryReceiptItem validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryreceiptitem ID format",
			NOT_FOUND: "DeliveryReceiptItem not found",
			CREATE_FAILED: "Error creating deliveryreceiptitem",
			UPDATE_FAILED: "Error updating deliveryreceiptitem",
			DELETE_FAILED: "Error deleting deliveryreceiptitem",
			GET_FAILED: "Error getting deliveryreceiptitem",
			GET_ALL_FAILED: "Error getting deliveryreceiptitems",
			ERROR_GETTING: "Error getting deliveryreceiptitem",
			ERROR_UPDATING: "Error updating deliveryreceiptitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		CATEGORY: {
			VALIDATION_FAILED: "Category validation failed",
			INVALID_ID_FORMAT: "Invalid category ID format",
			NOT_FOUND: "Category not found",
			CREATE_FAILED: "Error creating category",
			UPDATE_FAILED: "Error updating category",
			DELETE_FAILED: "Error deleting category",
			GET_FAILED: "Error getting category",
			GET_ALL_FAILED: "Error getting categorys",
			ERROR_GETTING: "Error getting category",
			ERROR_UPDATING: "Error updating category",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERY: {
			VALIDATION_FAILED: "Delivery validation failed",
			INVALID_ID_FORMAT: "Invalid delivery ID format",
			NOT_FOUND: "Delivery not found",
			CREATE_FAILED: "Error creating delivery",
			UPDATE_FAILED: "Error updating delivery",
			DELETE_FAILED: "Error deleting delivery",
			GET_FAILED: "Error getting delivery",
			GET_ALL_FAILED: "Error getting deliverys",
			ERROR_GETTING: "Error getting delivery",
			ERROR_UPDATING: "Error updating delivery",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYITEM: {
			VALIDATION_FAILED: "DeliveryItem validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryitem ID format",
			NOT_FOUND: "DeliveryItem not found",
			CREATE_FAILED: "Error creating deliveryitem",
			UPDATE_FAILED: "Error updating deliveryitem",
			DELETE_FAILED: "Error deleting deliveryitem",
			GET_FAILED: "Error getting deliveryitem",
			GET_ALL_FAILED: "Error getting deliveryitems",
			ERROR_GETTING: "Error getting deliveryitem",
			ERROR_UPDATING: "Error updating deliveryitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SUPPLIERITEM: {
			VALIDATION_FAILED: "SupplierItem validation failed",
			INVALID_ID_FORMAT: "Invalid supplieritem ID format",
			NOT_FOUND: "SupplierItem not found",
			CREATE_FAILED: "Error creating supplieritem",
			UPDATE_FAILED: "Error updating supplieritem",
			DELETE_FAILED: "Error deleting supplieritem",
			GET_FAILED: "Error getting supplieritem",
			GET_ALL_FAILED: "Error getting supplieritems",
			ERROR_GETTING: "Error getting supplieritem",
			ERROR_UPDATING: "Error updating supplieritem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SUBCATEGORY: {
			VALIDATION_FAILED: "SubCategory validation failed",
			INVALID_ID_FORMAT: "Invalid subcategory ID format",
			NOT_FOUND: "SubCategory not found",
			CREATE_FAILED: "Error creating subcategory",
			UPDATE_FAILED: "Error updating subcategory",
			DELETE_FAILED: "Error deleting subcategory",
			GET_FAILED: "Error getting subcategory",
			GET_ALL_FAILED: "Error getting subcategorys",
			ERROR_GETTING: "Error getting subcategory",
			ERROR_UPDATING: "Error updating subcategory",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		PRODUCTTYPE: {
			CREATE_FAILED: "Failed to create product type",
			GET_ALL_FAILED: "Failed to retrieve all product types",
			NOT_FOUND: "Product type not found",
			ERROR_GETTING: "Error getting product type",
			ERROR_UPDATING: "Error updating product type",
			DELETE_FAILED: "Failed to delete product type",
		},
		ALERT: {
			VALIDATION_FAILED: "Alert validation failed",
			INVALID_ID_FORMAT: "Invalid alert ID format",
			NOT_FOUND: "Alert not found",
			CREATE_FAILED: "Error creating alert",
			UPDATE_FAILED: "Error updating alert",
			DELETE_FAILED: "Error deleting alert",
			GET_FAILED: "Error getting alert",
			GET_ALL_FAILED: "Error getting alerts",
			ERROR_GETTING: "Error getting alert",
			ERROR_UPDATING: "Error updating alert",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		ACTIVITYLOG: {
			VALIDATION_FAILED: "ActivityLog validation failed",
			INVALID_ID_FORMAT: "Invalid activitylog ID format",
			NOT_FOUND: "ActivityLog not found",
			CREATE_FAILED: "Error creating activitylog",
			UPDATE_FAILED: "Error updating activitylog",
			DELETE_FAILED: "Error deleting activitylog",
			GET_FAILED: "Error getting activitylog",
			GET_ALL_FAILED: "Error getting activitylogs",
			ERROR_GETTING: "Error getting activitylog",
			ERROR_UPDATING: "Error updating activitylog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		AUDITLOG: {
			VALIDATION_FAILED: "AuditLog validation failed",
			INVALID_ID_FORMAT: "Invalid auditlog ID format",
			NOT_FOUND: "AuditLog not found",
			CREATE_FAILED: "Error creating auditlog",
			UPDATE_FAILED: "Error updating auditlog",
			DELETE_FAILED: "Error deleting auditlog",
			GET_FAILED: "Error getting auditlog",
			GET_ALL_FAILED: "Error getting auditlogs",
			ERROR_GETTING: "Error getting auditlog",
			ERROR_UPDATING: "Error updating auditlog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		NOTIFICATION: {
			VALIDATION_FAILED: "Notification validation failed",
			INVALID_ID_FORMAT: "Invalid notification ID format",
			NOT_FOUND: "Notification not found",
			CREATE_FAILED: "Error creating notification",
			UPDATE_FAILED: "Error updating notification",
			DELETE_FAILED: "Error deleting notification",
			GET_FAILED: "Error getting notification",
			GET_ALL_FAILED: "Error getting notifications",
			ERROR_GETTING: "Error getting notification",
			ERROR_UPDATING: "Error updating notification",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SYSTEMLOG: {
			VALIDATION_FAILED: "SystemLog validation failed",
			INVALID_ID_FORMAT: "Invalid systemlog ID format",
			NOT_FOUND: "SystemLog not found",
			CREATE_FAILED: "Error creating systemlog",
			UPDATE_FAILED: "Error updating systemlog",
			DELETE_FAILED: "Error deleting systemlog",
			GET_FAILED: "Error getting systemlog",
			GET_ALL_FAILED: "Error getting systemlogs",
			ERROR_GETTING: "Error getting systemlog",
			ERROR_UPDATING: "Error updating systemlog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYORDER: {
			VALIDATION_FAILED: "DeliveryOrder validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryorder ID format",
			NOT_FOUND: "DeliveryOrder not found",
			CREATE_FAILED: "Error creating deliveryorder",
			UPDATE_FAILED: "Error updating deliveryorder",
			DELETE_FAILED: "Error deleting deliveryorder",
			GET_FAILED: "Error getting deliveryorder",
			GET_ALL_FAILED: "Error getting deliveryorders",
			ERROR_GETTING: "Error getting deliveryorder",
			ERROR_UPDATING: "Error updating deliveryorder",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		STOCKMOVEMENTITEM: {
			VALIDATION_FAILED: "StockMovementItem validation failed",
			INVALID_ID_FORMAT: "Invalid stockmovementitem ID format",
			NOT_FOUND: "StockMovementItem not found",
			CREATE_FAILED: "Error creating stockmovementitem",
			UPDATE_FAILED: "Error updating stockmovementitem",
			DELETE_FAILED: "Error deleting stockmovementitem",
			GET_FAILED: "Error getting stockmovementitem",
			GET_ALL_FAILED: "Error getting stockmovementitems",
			ERROR_GETTING: "Error getting stockmovementitem",
			ERROR_UPDATING: "Error updating stockmovementitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		PRICE: {
			VALIDATION_FAILED: "Price validation failed",
			INVALID_ID_FORMAT: "Invalid price ID format",
			NOT_FOUND: "Price not found",
			CREATE_FAILED: "Error creating price",
			UPDATE_FAILED: "Error updating price",
			DELETE_FAILED: "Error deleting price",
			GET_FAILED: "Error getting price",
			GET_ALL_FAILED: "Error getting prices",
			ERROR_GETTING: "Error getting price",
			ERROR_UPDATING: "Error updating price",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		DELIVERYORDERITEM: {
			VALIDATION_FAILED: "DeliveryOrderItem validation failed",
			INVALID_ID_FORMAT: "Invalid deliveryorderitem ID format",
			NOT_FOUND: "DeliveryOrderItem not found",
			CREATE_FAILED: "Error creating deliveryorderitem",
			UPDATE_FAILED: "Error updating deliveryorderitem",
			DELETE_FAILED: "Error deleting deliveryorderitem",
			GET_FAILED: "Error getting deliveryorderitem",
			GET_ALL_FAILED: "Error getting deliveryorderitems",
			ERROR_GETTING: "Error getting deliveryorderitem",
			ERROR_UPDATING: "Error updating deliveryorderitem",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		METRICS: {
			VALIDATION_FAILED: "Metrics validation failed",
			INVALID_ID_FORMAT: "Invalid metrics ID format",
			NOT_FOUND: "Metrics not found",
			CREATE_FAILED: "Error creating metrics",
			UPDATE_FAILED: "Error updating metrics",
			DELETE_FAILED: "Error deleting metrics",
			GET_FAILED: "Error getting metrics",
			GET_ALL_FAILED: "Error getting metrics",
			ERROR_GETTING: "Error getting metrics",
			ERROR_UPDATING: "Error updating metrics",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		PATIENT: {
			VALIDATION_FAILED: "Patient validation failed",
			INVALID_ID_FORMAT: "Invalid patient ID format",
			NOT_FOUND: "Patient not found",
			CREATE_FAILED: "Error creating patient",
			UPDATE_FAILED: "Error updating patient",
			DELETE_FAILED: "Error deleting patient",
			GET_FAILED: "Error getting patient",
			GET_ALL_FAILED: "Error getting patients",
			ERROR_GETTING: "Error getting patient",
			ERROR_UPDATING: "Error updating patient",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		MEDICINE: {
			VALIDATION_FAILED: "Medicine validation failed",
			INVALID_ID_FORMAT: "Invalid medicine ID format",
			NOT_FOUND: "Medicine not found",
			CREATE_FAILED: "Error creating medicine",
			UPDATE_FAILED: "Error updating medicine",
			DELETE_FAILED: "Error deleting medicine",
			GET_FAILED: "Error getting medicine",
			GET_ALL_FAILED: "Error getting medicines",
			ERROR_GETTING: "Error getting medicine",
			ERROR_UPDATING: "Error updating medicine",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		APPROVAL: {
			VALIDATION_FAILED: "Approval validation failed",
			INVALID_ID_FORMAT: "Invalid approval ID format",
			NOT_FOUND: "Approval not found",
			CREATE_FAILED: "Error creating approval",
			UPDATE_FAILED: "Error updating approval",
			DELETE_FAILED: "Error deleting approval",
			GET_FAILED: "Error getting approval",
			GET_ALL_FAILED: "Error getting approvals",
			ERROR_GETTING: "Error getting approval",
			ERROR_UPDATING: "Error updating approval",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},
	INFO: {
		USER: {
			REGISTERING_USER: "Registering user with email:",
			CREATING_USER_WITH_PERSON_ID: "Creating user with personId:",
			LOGGING_IN_USER: "Logging in user with email:",
		},
	},
	SUCCESS: {
		DELIVERYORDER: {
			CREATED_SUCCESSFUL: "Delivery order created successfully",
			RETRIEVED_SUCCESSFULLY: "Delivery order retrieved successfully",
			UPDATED_SUCCESSFULLY: "Delivery order updated successfully",
			DELETED_SUCCESSFULLY: "Delivery order deleted successfully",
			LIST_RETRIEVED: "Delivery order list retrieved successfully",
			STATUS_UPDATED: "Delivery order status updated successfully",
			ASSIGNED_SUCCESSFULLY: "Delivery order assigned successfully",
			DELIVERY_CONFIRMED: "Delivery order confirmed successfully",
			CREATED: "Delivery Orders created successfully",
			UPDATED: "Delivery Orders updated successfully",
			DELETED: "Delivery Orders deleted successfully",
			RETRIEVED: "Delivery Orders retrieved successfully",
			RETRIEVED_ALL: "Delivery Orders retrieved successfully",
			GETTING_BY_ID: "Getting Delivery Orders by ID",
		},
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		PERSON: {
			SOFT_DELETING: "Soft deleting user",
			CREATED: "Person created successfully",
			UPDATED: "Person updated successfully",
			DELETED: "Person deleted successfully",
			RETRIEVED: "Person retrieved successfully",
			RETRIEVED_ALL: "Persons retrieved successfully",
			GETTING_BY_ID: "Getting person by ID",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		ROLE: {
			CREATED: "Role created successfully",
			UPDATED: "Role updated successfully",
			DELETED: "Role deleted successfully",
			RETRIEVED: "Role retrieved successfully",
			RETRIEVED_ALL: "Roles retrieved successfully",
			GETTING_BY_ID: "Getting role by ID",
		},
		USER: {
			CREATED: "User created successfully",
			UPDATED: "User updated successfully",
			DELETED: "User deleted successfully",
			RETRIEVED: "User retrieved successfully",
			RETRIEVED_ALL: "Users retrieved successfully",
			GETTING_BY_ID: "Getting user by ID",
		},
		PRODUCT: {
			CREATED: "Product created successfully",
			UPDATED: "Product updated successfully",
			DELETED: "Product deleted successfully",
			RETRIEVED: "Product retrieved successfully",
			RETRIEVED_ALL: "Products retrieved successfully",
			GETTING_BY_ID: "Getting product by ID",
		},
		BATCH: {
			CREATED: "Batch created successfully",
			UPDATED: "Batch updated successfully",
			DELETED: "Batch deleted successfully",
			RETRIEVED: "Batch retrieved successfully",
			RETRIEVED_ALL: "Batchs retrieved successfully",
			GETTING_BY_ID: "Getting batch by ID",
		},
		STOCK: {
			CREATED: "Stock created successfully",
			UPDATED: "Stock updated successfully",
			DELETED: "Stock deleted successfully",
			RETRIEVED: "Stock retrieved successfully",
			RETRIEVED_ALL: "Stocks retrieved successfully",
			GETTING_BY_ID: "Getting stock by ID",
		},
		SUPPLIER: {
			CREATED: "Supplier created successfully",
			UPDATED: "Supplier updated successfully",
			DELETED: "Supplier deleted successfully",
			RETRIEVED: "Supplier retrieved successfully",
			RETRIEVED_ALL: "Suppliers retrieved successfully",
			GETTING_BY_ID: "Getting supplier by ID",
		},
		PURCHASEORDERITEM: {
			CREATED: "PurchaseOrderItem created successfully",
			UPDATED: "PurchaseOrderItem updated successfully",
			DELETED: "PurchaseOrderItem deleted successfully",
			RETRIEVED: "PurchaseOrderItem retrieved successfully",
			RETRIEVED_ALL: "PurchaseOrderItems retrieved successfully",
			GETTING_BY_ID: "Getting purchaseorderitem by ID",
		},
		TRANSACTION: {
			CREATED: "Transaction created successfully",
			UPDATED: "Transaction updated successfully",
			DELETED: "Transaction deleted successfully",
			RETRIEVED: "Transaction retrieved successfully",
			RETRIEVED_ALL: "Transactions retrieved successfully",
			GETTING_BY_ID: "Getting transaction by ID",
		},
		LOCATION: {
			CREATED: "Location created successfully",
			UPDATED: "Location updated successfully",
			DELETED: "Location deleted successfully",
			RETRIEVED: "Location retrieved successfully",
			RETRIEVED_ALL: "Locations retrieved successfully",
			GETTING_BY_ID: "Getting location by ID",
		},
		TRANSACTIONITEM: {
			CREATED: "TransactionItem created successfully",
			UPDATED: "TransactionItem updated successfully",
			DELETED: "TransactionItem deleted successfully",
			RETRIEVED: "TransactionItem retrieved successfully",
			RETRIEVED_ALL: "TransactionItems retrieved successfully",
			GETTING_BY_ID: "Getting transactionitem by ID",
		},
		STOCKRECORD: {
			CREATED: "Stock record created successfully",
			RETRIEVED: "Stock record retrieved successfully",
			RETRIEVED_ALL: "Stock records retrieved successfully",
			UPDATED: "Stock record updated successfully",
			DELETED: "Stock record deleted successfully",
			GETTING_BY_ID: "Fetching stock record by ID",
		},
		DELIVERORDER: {
			CREATED: "DeliverOrder created successfully",
			UPDATED: "DeliverOrder updated successfully",
			DELETED: "DeliverOrder deleted successfully",
			RETRIEVED: "DeliverOrder retrieved successfully",
			RETRIEVED_ALL: "DeliverOrders retrieved successfully",
			GETTING_BY_ID: "Getting deliverorder by ID",
		},
		ORGANIZATION: {
			CREATED: "Organization created successfully",
			UPDATED: "Organization updated successfully",
			DELETED: "Organization deleted successfully",
			RETRIEVED: "Organization retrieved successfully",
			RETRIEVED_ALL: "Organizations retrieved successfully",
			GETTING_BY_ID: "Getting organization by ID",
		},
		DELIVERYRECEIPT: {
			CREATED: "DeliveryReceipt created successfully",
			UPDATED: "DeliveryReceipt updated successfully",
			DELETED: "DeliveryReceipt deleted successfully",
			RETRIEVED: "DeliveryReceipt retrieved successfully",
			RETRIEVED_ALL: "DeliveryReceipts retrieved successfully",
			GETTING_BY_ID: "Getting deliveryreceipt by ID",
		},
		DELIVERYREQUEST: {
			CREATED: "DeliveryRequest created successfully",
			UPDATED: "DeliveryRequest updated successfully",
			DELETED: "DeliveryRequest deleted successfully",
			RETRIEVED: "DeliveryRequest retrieved successfully",
			RETRIEVED_ALL: "DeliveryRequests retrieved successfully",
			GETTING_BY_ID: "Getting deliveryrequest by ID",
		},
		DELIVERYREQUESTITEM: {
			CREATED: "DeliveryRequestItem created successfully",
			UPDATED: "DeliveryRequestItem updated successfully",
			DELETED: "DeliveryRequestItem deleted successfully",
			RETRIEVED: "DeliveryRequestItem retrieved successfully",
			RETRIEVED_ALL: "DeliveryRequestItems retrieved successfully",
			GETTING_BY_ID: "Getting deliveryrequestitem by ID",
		},
		DELIVERYRECEIPTITEM: {
			CREATED: "DeliveryReceiptItem created successfully",
			UPDATED: "DeliveryReceiptItem updated successfully",
			DELETED: "DeliveryReceiptItem deleted successfully",
			RETRIEVED: "DeliveryReceiptItem retrieved successfully",
			RETRIEVED_ALL: "DeliveryReceiptItems retrieved successfully",
			GETTING_BY_ID: "Getting deliveryreceiptitem by ID",
		},
		CATEGORY: {
			CREATED: "Category created successfully",
			UPDATED: "Category updated successfully",
			DELETED: "Category deleted successfully",
			RETRIEVED: "Category retrieved successfully",
			RETRIEVED_ALL: "Categorys retrieved successfully",
			GETTING_BY_ID: "Getting category by ID",
		},
		PRODUCTTYPE: {
			CREATED: "Product type created successfully",
			RETRIEVED_ALL: "Product types retrieved successfully",
			RETRIEVED: "Product type retrieved successfully",
			UPDATED: "Product type updated successfully",
			DELETED: "Product type deleted successfully",
			GETTING_BY_ID: "Getting product type by ID",
		},
		DELIVERY: {
			CREATED: "Delivery created successfully",
			UPDATED: "Delivery updated successfully",
			DELETED: "Delivery deleted successfully",
			RETRIEVED: "Delivery retrieved successfully",
			RETRIEVED_ALL: "Deliverys retrieved successfully",
			GETTING_BY_ID: "Getting delivery by ID",
		},
		ITEM: {
			CREATED: "Item created successfully",
			UPDATED: "Item updated successfully",
			DELETED: "Item deleted successfully",
			RETRIEVED: "Item retrieved successfully",
			RETRIEVED_ALL: "Items retrieved successfully",
			GETTING_BY_ID: "Getting item by ID",
		},
		DELIVERYITEM: {
			CREATED: "DeliveryItem created successfully",
			UPDATED: "DeliveryItem updated successfully",
			DELETED: "DeliveryItem deleted successfully",
			RETRIEVED: "DeliveryItem retrieved successfully",
			RETRIEVED_ALL: "DeliveryItems retrieved successfully",
			GETTING_BY_ID: "Getting deliveryitem by ID",
		},
		SUPPLIERITEM: {
			CREATED: "SupplierItem created successfully",
			UPDATED: "SupplierItem updated successfully",
			DELETED: "SupplierItem deleted successfully",
			RETRIEVED: "SupplierItem retrieved successfully",
			RETRIEVED_ALL: "SupplierItems retrieved successfully",
			GETTING_BY_ID: "Getting supplieritem by ID",
		},
		SUBCATEGORY: {
			CREATED: "SubCategory created successfully",
			UPDATED: "SubCategory updated successfully",
			DELETED: "SubCategory deleted successfully",
			RETRIEVED: "SubCategory retrieved successfully",
			RETRIEVED_ALL: "SubCategorys retrieved successfully",
			GETTING_BY_ID: "Getting subcategory by ID",
		},
		ALERT: {
			CREATED: "Alert created successfully",
			UPDATED: "Alert updated successfully",
			DELETED: "Alert deleted successfully",
			RETRIEVED: "Alert retrieved successfully",
			RETRIEVED_ALL: "Alerts retrieved successfully",
			GETTING_BY_ID: "Getting alert by ID",
		},
		ACTIVITYLOG: {
			CREATED: "ActivityLog created successfully",
			UPDATED: "ActivityLog updated successfully",
			DELETED: "ActivityLog deleted successfully",
			RETRIEVED: "ActivityLog retrieved successfully",
			RETRIEVED_ALL: "ActivityLogs retrieved successfully",
			GETTING_BY_ID: "Getting activitylog by ID",
		},
		AUDITLOG: {
			CREATED: "AuditLog created successfully",
			UPDATED: "AuditLog updated successfully",
			DELETED: "AuditLog deleted successfully",
			RETRIEVED: "AuditLog retrieved successfully",
			RETRIEVED_ALL: "AuditLogs retrieved successfully",
			GETTING_BY_ID: "Getting auditlog by ID",
		},
		NOTIFICATION: {
			CREATED: "Notification created successfully",
			UPDATED: "Notification updated successfully",
			DELETED: "Notification deleted successfully",
			RETRIEVED: "Notification retrieved successfully",
			RETRIEVED_ALL: "Notifications retrieved successfully",
			GETTING_BY_ID: "Getting notification by ID",
		},
		SYSTEMLOG: {
			CREATED: "SystemLog created successfully",
			UPDATED: "SystemLog updated successfully",
			DELETED: "SystemLog deleted successfully",
			RETRIEVED: "SystemLog retrieved successfully",
			RETRIEVED_ALL: "SystemLogs retrieved successfully",
			GETTING_BY_ID: "Getting systemlog by ID",
		},
		STOCKMOVEMENTITEM: {
			CREATED: "StockMovementItem created successfully",
			UPDATED: "StockMovementItem updated successfully",
			DELETED: "StockMovementItem deleted successfully",
			RETRIEVED: "StockMovementItem retrieved successfully",
			RETRIEVED_ALL: "StockMovementItems retrieved successfully",
			GETTING_BY_ID: "Getting stockmovementitem by ID",
		},
		PRICE: {
			CREATED: "Price created successfully",
			UPDATED: "Price updated successfully",
			DELETED: "Price deleted successfully",
			RETRIEVED: "Price retrieved successfully",
			RETRIEVED_ALL: "Prices retrieved successfully",
			GETTING_BY_ID: "Getting price by ID",
		},
		DELIVERYORDERITEM: {
			CREATED: "DeliveryOrderItem created successfully",
			UPDATED: "DeliveryOrderItem updated successfully",
			DELETED: "DeliveryOrderItem deleted successfully",
			RETRIEVED: "DeliveryOrderItem retrieved successfully",
			RETRIEVED_ALL: "DeliveryOrderItems retrieved successfully",
			GETTING_BY_ID: "Getting deliveryorderitem by ID",
		},
		METRICS: {
			CREATED: "Metrics created successfully",
			UPDATED: "Metrics updated successfully",
			DELETED: "Metrics deleted successfully",
			RETRIEVED: "Metrics retrieved successfully",
			RETRIEVED_ALL: "Metricss retrieved successfully",
			GETTING_BY_ID: "Getting metrics by ID",
		},
		PATIENT: {
			CREATED: "Patient created successfully",
			UPDATED: "Patient updated successfully",
			DELETED: "Patient deleted successfully",
			RETRIEVED: "Patient retrieved successfully",
			RETRIEVED_ALL: "Patients retrieved successfully",
			GETTING_BY_ID: "Getting patient by ID",
		},
		MEDICINE: {
			CREATED: "Medicine created successfully",
			UPDATED: "Medicine updated successfully",
			DELETED: "Medicine deleted successfully",
			RETRIEVED: "Medicine retrieved successfully",
			RETRIEVED_ALL: "Medicines retrieved successfully",
			GETTING_BY_ID: "Getting medicine by ID",
		},
		APPROVAL: {
			CREATED: "Approval created successfully",
			UPDATED: "Approval updated successfully",
			DELETED: "Approval deleted successfully",
			RETRIEVED: "Approval retrieved successfully",
			RETRIEVED_ALL: "Approvals retrieved successfully",
			GETTING_BY_ID: "Getting approval by ID",
		},
	},

	ACTIVITY_LOG: {
		APPROVAL: {
			ACTIONS: {
				CREATE_APPROVAL: "CREATE_APPROVAL",
				GET_ALL_APPROVAL: "GET_ALL_APPROVAL",
				GET_APPROVAL: "GET_APPROVAL",
				UPDATE_APPROVAL: "UPDATE_APPROVAL",
				DELETE_APPROVAL: "DELETE_APPROVAL",
			},
			DESCRIPTIONS: {
				APPROVAL_CREATED: "Created new approval",
				APPROVAL_UPDATED: "Updated approval",
				APPROVAL_DELETED: "Deleted approval",
				APPROVAL_RETRIEVED: "Retrieved approval details",
				APPROVALS_RETRIEVED: "Retrieved approval list",
			},
			PAGES: {
				APPROVAL_CREATION: "Approval Creation",
				APPROVAL_UPDATE: "Approval Update",
				APPROVAL_DELETION: "Approval Deletion",
				APPROVAL_DETAILS: "Approval Details",
				APPROVAL_LIST: "Approval List",
			},
		},
		MEDICINE: {
			ACTIONS: {
				CREATE_MEDICINE: "CREATE_MEDICINE",
				GET_ALL_MEDICINE: "GET_ALL_MEDICINE",
				GET_MEDICINE: "GET_MEDICINE",
				UPDATE_MEDICINE: "UPDATE_MEDICINE",
				DELETE_MEDICINE: "DELETE_MEDICINE",
			},
			DESCRIPTIONS: {
				MEDICINE_CREATED: "Created new medicine",
				MEDICINE_UPDATED: "Updated medicine",
				MEDICINE_DELETED: "Deleted medicine",
				MEDICINE_RETRIEVED: "Retrieved medicine details",
				MEDICINES_RETRIEVED: "Retrieved medicine list",
			},
			PAGES: {
				MEDICINE_CREATION: "Medicine Creation",
				MEDICINE_UPDATE: "Medicine Update",
				MEDICINE_DELETION: "Medicine Deletion",
				MEDICINE_DETAILS: "Medicine Details",
				MEDICINE_LIST: "Medicine List",
			},
		},
		PATIENT: {
			ACTIONS: {
				CREATE_PATIENT: "CREATE_PATIENT",
				GET_ALL_PATIENT: "GET_ALL_PATIENT",
				GET_PATIENT: "GET_PATIENT",
				UPDATE_PATIENT: "UPDATE_PATIENT",
				DELETE_PATIENT: "DELETE_PATIENT",
			},
			DESCRIPTIONS: {
				PATIENT_CREATED: "Created new patient",
				PATIENT_UPDATED: "Updated patient",
				PATIENT_DELETED: "Deleted patient",
				PATIENT_RETRIEVED: "Retrieved patient details",
				PATIENTS_RETRIEVED: "Retrieved patient list",
			},
			PAGES: {
				PATIENT_CREATION: "Patient Creation",
				PATIENT_UPDATE: "Patient Update",
				PATIENT_DELETION: "Patient Deletion",
				PATIENT_DETAILS: "Patient Details",
				PATIENT_LIST: "Patient List",
			},
		},
		ORGANIZATION: {
			ACTIONS: {
				CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
				GET_ALL_ORGANIZATIONS: "GET_ALL_ORGANIZATIONS",
				GET_ORGANIZATION: "GET_ORGANIZATION",
				UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
				DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
			},
			DESCRIPTIONS: {
				ORGANIZATION_CREATED: "Created new organization",
				ORGANIZATION_UPDATED: "Updated organization",
				ORGANIZATION_DELETED: "Deleted organization",
				ORGANIZATION_RETRIEVED: "Retrieved organization details",
				ORGANIZATIONS_RETRIEVED: "Retrieved organizations list",
			},
			PAGES: {
				ORGANIZATION_CREATION: "Organization Creation",
				ORGANIZATION_UPDATE: "Organization Update",
				ORGANIZATION_DELETION: "Organization Deletion",
				ORGANIZATION_DETAILS: "Organization Details",
				ORGANIZATIONS_LIST: "Organizations List",
			},
		},
		METRICS: {
			ACTIONS: {
				CREATE_METRICS: "CREATE_METRICS",
				GET_ALL_METRICS: "GET_ALL_METRICS",
				GET_METRICS: "GET_METRICS",
				UPDATE_METRICS: "UPDATE_METRICS",
				DELETE_METRICS: "DELETE_METRICS",
			},
			DESCRIPTIONS: {
				METRICS_CREATED: "Created new metrics",
				METRICS_UPDATED: "Updated metrics",
				METRICS_DELETED: "Deleted metrics",
				METRICS_RETRIEVED: "Retrieved metrics details",
				METRICSS_RETRIEVED: "Retrieved metrics list",
			},
			PAGES: {
				METRICS_CREATION: "Metrics Creation",
				METRICS_UPDATE: "Metrics Update",
				METRICS_DELETION: "Metrics Deletion",
				METRICS_DETAILS: "Metrics Details",
				METRICS_LIST: "Metrics List",
			},
		},
		DELIVERYORDERITEM: {
			ACTIONS: {
				CREATE_DELIVERYORDERITEM: "CREATE_DELIVERYORDERITEM",
				GET_ALL_DELIVERYORDERITEM: "GET_ALL_DELIVERYORDERITEM",
				GET_DELIVERYORDERITEM: "GET_DELIVERYORDERITEM",
				UPDATE_DELIVERYORDERITEM: "UPDATE_DELIVERYORDERITEM",
				DELETE_DELIVERYORDERITEM: "DELETE_DELIVERYORDERITEM",
			},
			DESCRIPTIONS: {
				DELIVERYORDERITEM_CREATED: "Created new deliveryorderitem",
				DELIVERYORDERITEM_UPDATED: "Updated deliveryorderitem",
				DELIVERYORDERITEM_DELETED: "Deleted deliveryorderitem",
				DELIVERYORDERITEM_RETRIEVED: "Retrieved deliveryorderitem details",
				DELIVERYORDERITEMS_RETRIEVED: "Retrieved deliveryorderitem list",
			},
			PAGES: {
				DELIVERYORDERITEM_CREATION: "DeliveryOrderItem Creation",
				DELIVERYORDERITEM_UPDATE: "DeliveryOrderItem Update",
				DELIVERYORDERITEM_DELETION: "DeliveryOrderItem Deletion",
				DELIVERYORDERITEM_DETAILS: "DeliveryOrderItem Details",
				DELIVERYORDERITEM_LIST: "DeliveryOrderItem List",
			},
		},
		PRICE: {
			ACTIONS: {
				CREATE_PRICE: "CREATE_PRICE",
				GET_ALL_PRICE: "GET_ALL_PRICE",
				GET_PRICE: "GET_PRICE",
				UPDATE_PRICE: "UPDATE_PRICE",
				DELETE_PRICE: "DELETE_PRICE",
			},
			DESCRIPTIONS: {
				PRICE_CREATED: "Created new price",
				PRICE_UPDATED: "Updated price",
				PRICE_DELETED: "Deleted price",
				PRICE_RETRIEVED: "Retrieved price details",
				PRICES_RETRIEVED: "Retrieved price list",
			},
			PAGES: {
				PRICE_CREATION: "Price Creation",
				PRICE_UPDATE: "Price Update",
				PRICE_DELETION: "Price Deletion",
				PRICE_DETAILS: "Price Details",
				PRICE_LIST: "Price List",
			},
		},
		STOCKMOVEMENTITEM: {
			ACTIONS: {
				CREATE_STOCKMOVEMENTITEM: "CREATE_STOCKMOVEMENTITEM",
				GET_ALL_STOCKMOVEMENTITEM: "GET_ALL_STOCKMOVEMENTITEM",
				GET_STOCKMOVEMENTITEM: "GET_STOCKMOVEMENTITEM",
				UPDATE_STOCKMOVEMENTITEM: "UPDATE_STOCKMOVEMENTITEM",
				DELETE_STOCKMOVEMENTITEM: "DELETE_STOCKMOVEMENTITEM",
			},
			DESCRIPTIONS: {
				STOCKMOVEMENTITEM_CREATED: "Created new stockmovementitem",
				STOCKMOVEMENTITEM_UPDATED: "Updated stockmovementitem",
				STOCKMOVEMENTITEM_DELETED: "Deleted stockmovementitem",
				STOCKMOVEMENTITEM_RETRIEVED: "Retrieved stockmovementitem details",
				STOCKMOVEMENTITEMS_RETRIEVED: "Retrieved stockmovementitem list",
			},
			PAGES: {
				STOCKMOVEMENTITEM_CREATION: "StockMovementItem Creation",
				STOCKMOVEMENTITEM_UPDATE: "StockMovementItem Update",
				STOCKMOVEMENTITEM_DELETION: "StockMovementItem Deletion",
				STOCKMOVEMENTITEM_DETAILS: "StockMovementItem Details",
				STOCKMOVEMENTITEM_LIST: "StockMovementItem List",
			},
		},
		DELIVERYORDER: {
			ACTIONS: {
				CREATE_DELIVERYORDER: "CREATE_DELIVERYORDER",
				GET_ALL_DELIVERYORDERS: "GET_ALL_DELIVERYORDERS",
				GET_DELIVERYORDER: "GET_DELIVERYORDER",
				UPDATE_DELIVERYORDER: "UPDATE_DELIVERYORDER",
				DELETE_DELIVERYORDER: "DELETE_DELIVERYORDER",
			},
			DESCRIPTIONS: {
				DELIVERYORDER_CREATED: "Created new delivery order",
				DELIVERYORDER_UPDATED: "Updated delivery order",
				DELIVERYORDER_DELETED: "Deleted delivery order",
				DELIVERYORDER_RETRIEVED: "Retrieved delivery order details",
				DELIVERYORDERS_RETRIEVED: "Retrieved delivery order list",
			},
			PAGES: {
				DELIVERYORDER_CREATION: "Delivery Order Creation",
				DELIVERYORDER_UPDATE: "Delivery Order Update",
				DELIVERYORDER_DELETION: "Delivery Order Deletion",
				DELIVERYORDER_DETAILS: "Delivery Order Details",
				DELIVERYORDER_LIST: "Delivery Order List",
			},
		},
		SYSTEMLOG: {
			ACTIONS: {
				CREATE_SYSTEMLOG: "CREATE_SYSTEMLOG",
				GET_ALL_SYSTEMLOG: "GET_ALL_SYSTEMLOG",
				GET_SYSTEMLOG: "GET_SYSTEMLOG",
				UPDATE_SYSTEMLOG: "UPDATE_SYSTEMLOG",
				DELETE_SYSTEMLOG: "DELETE_SYSTEMLOG",
			},
			DESCRIPTIONS: {
				SYSTEMLOG_CREATED: "Created new systemlog",
				SYSTEMLOG_UPDATED: "Updated systemlog",
				SYSTEMLOG_DELETED: "Deleted systemlog",
				SYSTEMLOG_RETRIEVED: "Retrieved systemlog details",
				SYSTEMLOGS_RETRIEVED: "Retrieved systemlog list",
			},
			PAGES: {
				SYSTEMLOG_CREATION: "SystemLog Creation",
				SYSTEMLOG_UPDATE: "SystemLog Update",
				SYSTEMLOG_DELETION: "SystemLog Deletion",
				SYSTEMLOG_DETAILS: "SystemLog Details",
				SYSTEMLOG_LIST: "SystemLog List",
			},
		},
		NOTIFICATION: {
			ACTIONS: {
				CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
				GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",
				GET_NOTIFICATION: "GET_NOTIFICATION",
				UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
				DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
			},
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
				NOTIFICATION_RETRIEVED: "Retrieved notification details",
				NOTIFICATIONS_RETRIEVED: "Retrieved notification list",
			},
			PAGES: {
				NOTIFICATION_CREATION: "Notification Creation",
				NOTIFICATION_UPDATE: "Notification Update",
				NOTIFICATION_DELETION: "Notification Deletion",
				NOTIFICATION_DETAILS: "Notification Details",
				NOTIFICATION_LIST: "Notification List",
			},
		},
		AUDITLOG: {
			ACTIONS: {
				CREATE_AUDITLOG: "CREATE_AUDITLOG",
				GET_ALL_AUDITLOG: "GET_ALL_AUDITLOG",
				GET_AUDITLOG: "GET_AUDITLOG",
				UPDATE_AUDITLOG: "UPDATE_AUDITLOG",
				DELETE_AUDITLOG: "DELETE_AUDITLOG",
			},
			DESCRIPTIONS: {
				AUDITLOG_CREATED: "Created new auditlog",
				AUDITLOG_UPDATED: "Updated auditlog",
				AUDITLOG_DELETED: "Deleted auditlog",
				AUDITLOG_RETRIEVED: "Retrieved auditlog details",
				AUDITLOGS_RETRIEVED: "Retrieved auditlog list",
			},
			PAGES: {
				AUDITLOG_CREATION: "AuditLog Creation",
				AUDITLOG_UPDATE: "AuditLog Update",
				AUDITLOG_DELETION: "AuditLog Deletion",
				AUDITLOG_DETAILS: "AuditLog Details",
				AUDITLOG_LIST: "AuditLog List",
			},
		},
		ACTIVITYLOG: {
			ACTIONS: {
				CREATE_ACTIVITYLOG: "CREATE_ACTIVITYLOG",
				GET_ALL_ACTIVITYLOG: "GET_ALL_ACTIVITYLOG",
				GET_ACTIVITYLOG: "GET_ACTIVITYLOG",
				UPDATE_ACTIVITYLOG: "UPDATE_ACTIVITYLOG",
				DELETE_ACTIVITYLOG: "DELETE_ACTIVITYLOG",
			},
			DESCRIPTIONS: {
				ACTIVITYLOG_CREATED: "Created new activitylog",
				ACTIVITYLOG_UPDATED: "Updated activitylog",
				ACTIVITYLOG_DELETED: "Deleted activitylog",
				ACTIVITYLOG_RETRIEVED: "Retrieved activitylog details",
				ACTIVITYLOGS_RETRIEVED: "Retrieved activitylog list",
			},
			PAGES: {
				ACTIVITYLOG_CREATION: "ActivityLog Creation",
				ACTIVITYLOG_UPDATE: "ActivityLog Update",
				ACTIVITYLOG_DELETION: "ActivityLog Deletion",
				ACTIVITYLOG_DETAILS: "ActivityLog Details",
				ACTIVITYLOG_LIST: "ActivityLog List",
			},
		},
		ALERT: {
			ACTIONS: {
				CREATE_ALERT: "CREATE_ALERT",
				GET_ALL_ALERT: "GET_ALL_ALERT",
				GET_ALERT: "GET_ALERT",
				UPDATE_ALERT: "UPDATE_ALERT",
				DELETE_ALERT: "DELETE_ALERT",
			},
			DESCRIPTIONS: {
				ALERT_CREATED: "Created new alert",
				ALERT_UPDATED: "Updated alert",
				ALERT_DELETED: "Deleted alert",
				ALERT_RETRIEVED: "Retrieved alert details",
				ALERTS_RETRIEVED: "Retrieved alert list",
			},
			PAGES: {
				ALERT_CREATION: "Alert Creation",
				ALERT_UPDATE: "Alert Update",
				ALERT_DELETION: "Alert Deletion",
				ALERT_DETAILS: "Alert Details",
				ALERT_LIST: "Alert List",
			},
		},
		SUBCATEGORY: {
			ACTIONS: {
				CREATE_SUBCATEGORY: "CREATE_SUBCATEGORY",
				GET_ALL_SUBCATEGORY: "GET_ALL_SUBCATEGORY",
				GET_SUBCATEGORY: "GET_SUBCATEGORY",
				UPDATE_SUBCATEGORY: "UPDATE_SUBCATEGORY",
				DELETE_SUBCATEGORY: "DELETE_SUBCATEGORY",
			},
			DESCRIPTIONS: {
				SUBCATEGORY_CREATED: "Created new subcategory",
				SUBCATEGORY_UPDATED: "Updated subcategory",
				SUBCATEGORY_DELETED: "Deleted subcategory",
				SUBCATEGORY_RETRIEVED: "Retrieved subcategory details",
				SUBCATEGORYS_RETRIEVED: "Retrieved subcategory list",
			},
			PAGES: {
				SUBCATEGORY_CREATION: "SubCategory Creation",
				SUBCATEGORY_UPDATE: "SubCategory Update",
				SUBCATEGORY_DELETION: "SubCategory Deletion",
				SUBCATEGORY_DETAILS: "SubCategory Details",
				SUBCATEGORY_LIST: "SubCategory List",
			},
		},
		PRODUCTTYPE: {
			ACTIONS: {
				CREATE_PRODUCTTYPE: "create_product_type",
				UPDATE_PRODUCTTYPE: "update_product_type",
				DELETE_PRODUCTTYPE: "delete_product_type",
			},
			DESCRIPTIONS: {
				PRODUCTTYPE_CREATED: "Product type created",
				PRODUCTTYPE_UPDATED: "Product type updated",
				PRODUCTTYPE_DELETED: "Product type deleted",
			},
			PAGES: {
				PRODUCTTYPE_CREATION: "Product Type Creation",
				PRODUCTTYPE_UPDATE: "Product Type Update",
				PRODUCTTYPE_DELETION: "Product Type Deletion",
			},
		},

		SUPPLIERITEM: {
			ACTIONS: {
				CREATE_SUPPLIERITEM: "CREATE_SUPPLIERITEM",
				GET_ALL_SUPPLIERITEM: "GET_ALL_SUPPLIERITEM",
				GET_SUPPLIERITEM: "GET_SUPPLIERITEM",
				UPDATE_SUPPLIERITEM: "UPDATE_SUPPLIERITEM",
				DELETE_SUPPLIERITEM: "DELETE_SUPPLIERITEM",
			},
			DESCRIPTIONS: {
				SUPPLIERITEM_CREATED: "Created new supplieritem",
				SUPPLIERITEM_UPDATED: "Updated supplieritem",
				SUPPLIERITEM_DELETED: "Deleted supplieritem",
				SUPPLIERITEM_RETRIEVED: "Retrieved supplieritem details",
				SUPPLIERITEMS_RETRIEVED: "Retrieved supplieritem list",
			},
			PAGES: {
				SUPPLIERITEM_CREATION: "SupplierItem Creation",
				SUPPLIERITEM_UPDATE: "SupplierItem Update",
				SUPPLIERITEM_DELETION: "SupplierItem Deletion",
				SUPPLIERITEM_DETAILS: "SupplierItem Details",
				SUPPLIERITEM_LIST: "SupplierItem List",
			},
		},
		DELIVERYITEM: {
			ACTIONS: {
				CREATE_DELIVERYITEM: "CREATE_DELIVERYITEM",
				GET_ALL_DELIVERYITEM: "GET_ALL_DELIVERYITEM",
				GET_DELIVERYITEM: "GET_DELIVERYITEM",
				UPDATE_DELIVERYITEM: "UPDATE_DELIVERYITEM",
				DELETE_DELIVERYITEM: "DELETE_DELIVERYITEM",
			},
			DESCRIPTIONS: {
				DELIVERYITEM_CREATED: "Created new deliveryitem",
				DELIVERYITEM_UPDATED: "Updated deliveryitem",
				DELIVERYITEM_DELETED: "Deleted deliveryitem",
				DELIVERYITEM_RETRIEVED: "Retrieved deliveryitem details",
				DELIVERYITEMS_RETRIEVED: "Retrieved deliveryitem list",
			},
			PAGES: {
				DELIVERYITEM_CREATION: "DeliveryItem Creation",
				DELIVERYITEM_UPDATE: "DeliveryItem Update",
				DELIVERYITEM_DELETION: "DeliveryItem Deletion",
				DELIVERYITEM_DETAILS: "DeliveryItem Details",
				DELIVERYITEM_LIST: "DeliveryItem List",
			},
		},
		ITEM: {
			ACTIONS: {
				CREATE_ITEM: "CREATE_ITEM",
				GET_ALL_ITEM: "GET_ALL_ITEM",
				GET_ITEM: "GET_ITEM",
				UPDATE_ITEM: "UPDATE_ITEM",
				DELETE_ITEM: "DELETE_ITEM",
			},
			DESCRIPTIONS: {
				ITEM_CREATED: "Created new item",
				ITEM_UPDATED: "Updated item",
				ITEM_DELETED: "Deleted item",
				ITEM_RETRIEVED: "Retrieved item details",
				ITEMS_RETRIEVED: "Retrieved item list",
			},
			PAGES: {
				ITEM_CREATION: "Item Creation",
				ITEM_UPDATE: "Item Update",
				ITEM_DELETION: "Item Deletion",
				ITEM_DETAILS: "Item Details",
				ITEM_LIST: "Item List",
			},
		},
		DELIVERY: {
			ACTIONS: {
				CREATE_DELIVERY: "CREATE_DELIVERY",
				GET_ALL_DELIVERY: "GET_ALL_DELIVERY",
				GET_DELIVERY: "GET_DELIVERY",
				UPDATE_DELIVERY: "UPDATE_DELIVERY",
				DELETE_DELIVERY: "DELETE_DELIVERY",
			},
			DESCRIPTIONS: {
				DELIVERY_CREATED: "Created new delivery",
				DELIVERY_UPDATED: "Updated delivery",
				DELIVERY_DELETED: "Deleted delivery",
				DELIVERY_RETRIEVED: "Retrieved delivery details",
				DELIVERYS_RETRIEVED: "Retrieved delivery list",
			},
			PAGES: {
				DELIVERY_CREATION: "Delivery Creation",
				DELIVERY_UPDATE: "Delivery Update",
				DELIVERY_DELETION: "Delivery Deletion",
				DELIVERY_DETAILS: "Delivery Details",
				DELIVERY_LIST: "Delivery List",
			},
		},
		CATEGORY: {
			ACTIONS: {
				CREATE_CATEGORY: "CREATE_CATEGORY",
				GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
				GET_CATEGORY: "GET_CATEGORY",
				UPDATE_CATEGORY: "UPDATE_CATEGORY",
				DELETE_CATEGORY: "DELETE_CATEGORY",
			},
			DESCRIPTIONS: {
				CATEGORY_CREATED: "Created new category",
				CATEGORY_UPDATED: "Updated category",
				CATEGORY_DELETED: "Deleted category",
				CATEGORY_RETRIEVED: "Retrieved category details",
				CATEGORYS_RETRIEVED: "Retrieved category list",
			},
			PAGES: {
				CATEGORY_CREATION: "Category Creation",
				CATEGORY_UPDATE: "Category Update",
				CATEGORY_DELETION: "Category Deletion",
				CATEGORY_DETAILS: "Category Details",
				CATEGORY_LIST: "Category List",
			},
		},
		DELIVERYRECEIPTITEM: {
			ACTIONS: {
				CREATE_DELIVERYRECEIPTITEM: "CREATE_DELIVERYRECEIPTITEM",
				GET_ALL_DELIVERYRECEIPTITEM: "GET_ALL_DELIVERYRECEIPTITEM",
				GET_DELIVERYRECEIPTITEM: "GET_DELIVERYRECEIPTITEM",
				UPDATE_DELIVERYRECEIPTITEM: "UPDATE_DELIVERYRECEIPTITEM",
				DELETE_DELIVERYRECEIPTITEM: "DELETE_DELIVERYRECEIPTITEM",
			},
			DESCRIPTIONS: {
				DELIVERYRECEIPTITEM_CREATED: "Created new deliveryreceiptitem",
				DELIVERYRECEIPTITEM_UPDATED: "Updated deliveryreceiptitem",
				DELIVERYRECEIPTITEM_DELETED: "Deleted deliveryreceiptitem",
				DELIVERYRECEIPTITEM_RETRIEVED: "Retrieved deliveryreceiptitem details",
				DELIVERYRECEIPTITEMS_RETRIEVED: "Retrieved deliveryreceiptitem list",
			},
			PAGES: {
				DELIVERYRECEIPTITEM_CREATION: "DeliveryReceiptItem Creation",
				DELIVERYRECEIPTITEM_UPDATE: "DeliveryReceiptItem Update",
				DELIVERYRECEIPTITEM_DELETION: "DeliveryReceiptItem Deletion",
				DELIVERYRECEIPTITEM_DETAILS: "DeliveryReceiptItem Details",
				DELIVERYRECEIPTITEM_LIST: "DeliveryReceiptItem List",
			},
		},
		DELIVERYREQUESTITEM: {
			ACTIONS: {
				CREATE_DELIVERYREQUESTITEM: "CREATE_DELIVERYREQUESTITEM",
				GET_ALL_DELIVERYREQUESTITEM: "GET_ALL_DELIVERYREQUESTITEM",
				GET_DELIVERYREQUESTITEM: "GET_DELIVERYREQUESTITEM",
				UPDATE_DELIVERYREQUESTITEM: "UPDATE_DELIVERYREQUESTITEM",
				DELETE_DELIVERYREQUESTITEM: "DELETE_DELIVERYREQUESTITEM",
			},
			DESCRIPTIONS: {
				DELIVERYREQUESTITEM_CREATED: "Created new deliveryrequestitem",
				DELIVERYREQUESTITEM_UPDATED: "Updated deliveryrequestitem",
				DELIVERYREQUESTITEM_DELETED: "Deleted deliveryrequestitem",
				DELIVERYREQUESTITEM_RETRIEVED: "Retrieved deliveryrequestitem details",
				DELIVERYREQUESTITEMS_RETRIEVED: "Retrieved deliveryrequestitem list",
			},
			PAGES: {
				DELIVERYREQUESTITEM_CREATION: "DeliveryRequestItem Creation",
				DELIVERYREQUESTITEM_UPDATE: "DeliveryRequestItem Update",
				DELIVERYREQUESTITEM_DELETION: "DeliveryRequestItem Deletion",
				DELIVERYREQUESTITEM_DETAILS: "DeliveryRequestItem Details",
				DELIVERYREQUESTITEM_LIST: "DeliveryRequestItem List",
			},
		},
		DELIVERYREQUEST: {
			ACTIONS: {
				CREATE_DELIVERYREQUEST: "CREATE_DELIVERYREQUEST",
				GET_ALL_DELIVERYREQUEST: "GET_ALL_DELIVERYREQUEST",
				GET_DELIVERYREQUEST: "GET_DELIVERYREQUEST",
				UPDATE_DELIVERYREQUEST: "UPDATE_DELIVERYREQUEST",
				DELETE_DELIVERYREQUEST: "DELETE_DELIVERYREQUEST",
			},
			DESCRIPTIONS: {
				DELIVERYREQUEST_CREATED: "Created new deliveryrequest",
				DELIVERYREQUEST_UPDATED: "Updated deliveryrequest",
				DELIVERYREQUEST_DELETED: "Deleted deliveryrequest",
				DELIVERYREQUEST_RETRIEVED: "Retrieved deliveryrequest details",
				DELIVERYREQUESTS_RETRIEVED: "Retrieved deliveryrequest list",
			},
			PAGES: {
				DELIVERYREQUEST_CREATION: "DeliveryRequest Creation",
				DELIVERYREQUEST_UPDATE: "DeliveryRequest Update",
				DELIVERYREQUEST_DELETION: "DeliveryRequest Deletion",
				DELIVERYREQUEST_DETAILS: "DeliveryRequest Details",
				DELIVERYREQUEST_LIST: "DeliveryRequest List",
			},
		},
		DELIVERYRECEIPT: {
			ACTIONS: {
				CREATE_DELIVERYRECEIPT: "CREATE_DELIVERYRECEIPT",
				GET_ALL_DELIVERYRECEIPT: "GET_ALL_DELIVERYRECEIPT",
				GET_DELIVERYRECEIPT: "GET_DELIVERYRECEIPT",
				UPDATE_DELIVERYRECEIPT: "UPDATE_DELIVERYRECEIPT",
				DELETE_DELIVERYRECEIPT: "DELETE_DELIVERYRECEIPT",
			},
			DESCRIPTIONS: {
				DELIVERYRECEIPT_CREATED: "Created new deliveryreceipt",
				DELIVERYRECEIPT_UPDATED: "Updated deliveryreceipt",
				DELIVERYRECEIPT_DELETED: "Deleted deliveryreceipt",
				DELIVERYRECEIPT_RETRIEVED: "Retrieved deliveryreceipt details",
				DELIVERYRECEIPTS_RETRIEVED: "Retrieved deliveryreceipt list",
			},
			PAGES: {
				DELIVERYRECEIPT_CREATION: "DeliveryReceipt Creation",
				DELIVERYRECEIPT_UPDATE: "DeliveryReceipt Update",
				DELIVERYRECEIPT_DELETION: "DeliveryReceipt Deletion",
				DELIVERYRECEIPT_DETAILS: "DeliveryReceipt Details",
				DELIVERYRECEIPT_LIST: "DeliveryReceipt List",
			},
		},
		DELIVERORDER: {
			ACTIONS: {
				CREATE_DELIVERORDER: "CREATE_DELIVERORDER",
				GET_ALL_DELIVERORDER: "GET_ALL_DELIVERORDER",
				GET_DELIVERORDER: "GET_DELIVERORDER",
				UPDATE_DELIVERORDER: "UPDATE_DELIVERORDER",
				DELETE_DELIVERORDER: "DELETE_DELIVERORDER",
			},
			DESCRIPTIONS: {
				DELIVERORDER_CREATED: "Created new deliverorder",
				DELIVERORDER_UPDATED: "Updated deliverorder",
				DELIVERORDER_DELETED: "Deleted deliverorder",
				DELIVERORDER_RETRIEVED: "Retrieved deliverorder details",
				DELIVERORDERS_RETRIEVED: "Retrieved deliverorder list",
			},
			PAGES: {
				DELIVERORDER_CREATION: "DeliverOrder Creation",
				DELIVERORDER_UPDATE: "DeliverOrder Update",
				DELIVERORDER_DELETION: "DeliverOrder Deletion",
				DELIVERORDER_DETAILS: "DeliverOrder Details",
				DELIVERORDER_LIST: "DeliverOrder List",
			},
		},
		STOCKRECORD: {
			ACTIONS: {
				CREATE_STOCKRECORD: "CREATE_STOCKRECORD",
				UPDATE_STOCKRECORD: "UPDATE_STOCKRECORD",
				DELETE_STOCKRECORD: "DELETE_STOCKRECORD",
				VIEW_STOCKRECORD: "VIEW_STOCKRECORD",
				VIEW_STOCKRECORDS: "VIEW_STOCKRECORDS",
				STOCK_IN: "stock_in", // Receiving goods, purchase, return, etc.
				STOCK_OUT: "stock_out", // Issuing, dispensing, consumption
			},
			DESCRIPTIONS: {
				STOCKRECORD_CREATED: "Created new stock record",
				STOCKRECORD_UPDATED: "Updated stock record",
				STOCKRECORD_DELETED: "Deleted stock record",
			},
			PAGES: {
				STOCKRECORD_CREATION: "Stock Record - Create",
				STOCKRECORD_LIST: "Stock Records - List",
			},
		},
		TRANSACTIONITEM: {
			ACTIONS: {
				CREATE_TRANSACTIONITEM: "CREATE_TRANSACTIONITEM",
				GET_ALL_TRANSACTIONITEM: "GET_ALL_TRANSACTIONITEM",
				GET_TRANSACTIONITEM: "GET_TRANSACTIONITEM",
				UPDATE_TRANSACTIONITEM: "UPDATE_TRANSACTIONITEM",
				DELETE_TRANSACTIONITEM: "DELETE_TRANSACTIONITEM",
			},
			DESCRIPTIONS: {
				TRANSACTIONITEM_CREATED: "Created new transactionitem",
				TRANSACTIONITEM_UPDATED: "Updated transactionitem",
				TRANSACTIONITEM_DELETED: "Deleted transactionitem",
				TRANSACTIONITEM_RETRIEVED: "Retrieved transactionitem details",
				TRANSACTIONITEMS_RETRIEVED: "Retrieved transactionitem list",
			},
			PAGES: {
				TRANSACTIONITEM_CREATION: "TransactionItem Creation",
				TRANSACTIONITEM_UPDATE: "TransactionItem Update",
				TRANSACTIONITEM_DELETION: "TransactionItem Deletion",
				TRANSACTIONITEM_DETAILS: "TransactionItem Details",
				TRANSACTIONITEM_LIST: "TransactionItem List",
			},
		},
		LOCATION: {
			ACTIONS: {
				CREATE_LOCATION: "CREATE_LOCATION",
				GET_ALL_LOCATION: "GET_ALL_LOCATION",
				GET_LOCATION: "GET_LOCATION",
				UPDATE_LOCATION: "UPDATE_LOCATION",
				DELETE_LOCATION: "DELETE_LOCATION",
			},
			DESCRIPTIONS: {
				LOCATION_CREATED: "Created new location",
				LOCATION_UPDATED: "Updated location",
				LOCATION_DELETED: "Deleted location",
				LOCATION_RETRIEVED: "Retrieved location details",
				LOCATIONS_RETRIEVED: "Retrieved location list",
			},
			PAGES: {
				LOCATION_CREATION: "Location Creation",
				LOCATION_UPDATE: "Location Update",
				LOCATION_DELETION: "Location Deletion",
				LOCATION_DETAILS: "Location Details",
				LOCATION_LIST: "Location List",
			},
		},
		TRANSACTION: {
			ACTIONS: {
				CREATE_TRANSACTION: "CREATE_TRANSACTION",
				GET_ALL_TRANSACTION: "GET_ALL_TRANSACTION",
				GET_TRANSACTION: "GET_TRANSACTION",
				UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
				DELETE_TRANSACTION: "DELETE_TRANSACTION",
			},
			DESCRIPTIONS: {
				TRANSACTION_CREATED: "Created new transaction",
				TRANSACTION_UPDATED: "Updated transaction",
				TRANSACTION_DELETED: "Deleted transaction",
				TRANSACTION_RETRIEVED: "Retrieved transaction details",
				TRANSACTIONS_RETRIEVED: "Retrieved transaction list",
			},
			PAGES: {
				TRANSACTION_CREATION: "Transaction Creation",
				TRANSACTION_UPDATE: "Transaction Update",
				TRANSACTION_DELETION: "Transaction Deletion",
				TRANSACTION_DETAILS: "Transaction Details",
				TRANSACTION_LIST: "Transaction List",
			},
		},
		USER: {
			ACTIONS: {
				REGISTER: "REGISTER_USER",
				CREATE_USER: "CREATE_USER",
				GET_ALL_USER: "GET_ALL_USER",
				GET_USER: "GET_USER",
				UPDATE_USER: "UPDATE_USER",
				DELETE_USER: "DELETE_USER",
			},
			DESCRIPTIONS: {
				USER_REGISTERED: "Registered User",
				USER_CREATED: "Created new USER",
				USER_UPDATED: "Updated USER",
				USER_DELETED: "Deleted USER",
				USER_RETRIEVED: "Retrieved USER details",
				USERS_RETRIEVED: "Retrieved USER list",
			},
			PAGES: {
				USER_CREATION: "USER Creation",
				USER_UPDATE: "USER Update",
				USER_DELETION: "USER Deletion",
				USER_DETAILS: "USER Details",
				USER_LIST: "USER List",
			},
		},
		PURCHASEORDERITEM: {
			ACTIONS: {
				CREATE_PURCHASEORDERITEM: "CREATE_PURCHASEORDERITEM",
				GET_ALL_PURCHASEORDERITEM: "GET_ALL_PURCHASEORDERITEM",
				GET_PURCHASEORDERITEM: "GET_PURCHASEORDERITEM",
				UPDATE_PURCHASEORDERITEM: "UPDATE_PURCHASEORDERITEM",
				DELETE_PURCHASEORDERITEM: "DELETE_PURCHASEORDERITEM",
			},
			DESCRIPTIONS: {
				PURCHASEORDERITEM_CREATED: "Created new purchaseorderitem",
				PURCHASEORDERITEM_UPDATED: "Updated purchaseorderitem",
				PURCHASEORDERITEM_DELETED: "Deleted purchaseorderitem",
				PURCHASEORDERITEM_RETRIEVED: "Retrieved purchaseorderitem details",
				PURCHASEORDERITEMS_RETRIEVED: "Retrieved purchaseorderitem list",
			},
			PAGES: {
				PURCHASEORDERITEM_CREATION: "PurchaseOrderItem Creation",
				PURCHASEORDERITEM_UPDATE: "PurchaseOrderItem Update",
				PURCHASEORDERITEM_DELETION: "PurchaseOrderItem Deletion",
				PURCHASEORDERITEM_DETAILS: "PurchaseOrderItem Details",
				PURCHASEORDERITEM_LIST: "PurchaseOrderItem List",
			},
		},
		SUPPLIER: {
			ACTIONS: {
				CREATE_SUPPLIER: "CREATE_SUPPLIER",
				GET_ALL_SUPPLIER: "GET_ALL_SUPPLIER",
				GET_SUPPLIER: "GET_SUPPLIER",
				UPDATE_SUPPLIER: "UPDATE_SUPPLIER",
				DELETE_SUPPLIER: "DELETE_SUPPLIER",
			},
			DESCRIPTIONS: {
				SUPPLIER_CREATED: "Created new supplier",
				SUPPLIER_UPDATED: "Updated supplier",
				SUPPLIER_DELETED: "Deleted supplier",
				SUPPLIER_RETRIEVED: "Retrieved supplier details",
				SUPPLIERS_RETRIEVED: "Retrieved supplier list",
			},
			PAGES: {
				SUPPLIER_CREATION: "Supplier Creation",
				SUPPLIER_UPDATE: "Supplier Update",
				SUPPLIER_DELETION: "Supplier Deletion",
				SUPPLIER_DETAILS: "Supplier Details",
				SUPPLIER_LIST: "Supplier List",
			},
		},
		STOCK: {
			ACTIONS: {
				CREATE_STOCK: "CREATE_STOCK",
				GET_ALL_STOCK: "GET_ALL_STOCK",
				GET_STOCK: "GET_STOCK",
				UPDATE_STOCK: "UPDATE_STOCK",
				DELETE_STOCK: "DELETE_STOCK",
			},
			DESCRIPTIONS: {
				STOCK_CREATED: "Created new stock",
				STOCK_UPDATED: "Updated stock",
				STOCK_DELETED: "Deleted stock",
				STOCK_RETRIEVED: "Retrieved stock details",
				STOCKS_RETRIEVED: "Retrieved stock list",
			},
			PAGES: {
				STOCK_CREATION: "Stock Creation",
				STOCK_UPDATE: "Stock Update",
				STOCK_DELETION: "Stock Deletion",
				STOCK_DETAILS: "Stock Details",
				STOCK_LIST: "Stock List",
			},
		},
		BATCH: {
			ACTIONS: {
				CREATE_BATCH: "CREATE_BATCH",
				GET_ALL_BATCH: "GET_ALL_BATCH",
				GET_BATCH: "GET_BATCH",
				UPDATE_BATCH: "UPDATE_BATCH",
				DELETE_BATCH: "DELETE_BATCH",
			},
			DESCRIPTIONS: {
				BATCH_CREATED: "Created new batch",
				BATCH_UPDATED: "Updated batch",
				BATCH_DELETED: "Deleted batch",
				BATCH_RETRIEVED: "Retrieved batch details",
				BATCHS_RETRIEVED: "Retrieved batch list",
			},
			PAGES: {
				BATCH_CREATION: "Batch Creation",
				BATCH_UPDATE: "Batch Update",
				BATCH_DELETION: "Batch Deletion",
				BATCH_DETAILS: "Batch Details",
				BATCH_LIST: "Batch List",
			},
		},
		PRODUCT: {
			ACTIONS: {
				CREATE_PRODUCT: "CREATE_PRODUCT",
				GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
				GET_PRODUCT: "GET_PRODUCT",
				UPDATE_PRODUCT: "UPDATE_PRODUCT",
				DELETE_PRODUCT: "DELETE_PRODUCT",
			},
			DESCRIPTIONS: {
				PRODUCT_CREATED: "Created new product",
				PRODUCT_UPDATED: "Updated product",
				PRODUCT_DELETED: "Deleted product",
				PRODUCT_RETRIEVED: "Retrieved product details",
				PRODUCTS_RETRIEVED: "Retrieved product list",
			},
			PAGES: {
				PRODUCT_CREATION: "Product Creation",
				PRODUCT_UPDATE: "Product Update",
				PRODUCT_DELETION: "Product Deletion",
				PRODUCT_DETAILS: "Product Details",
				PRODUCT_LIST: "Product List",
			},
		},
		ROLE: {
			ACTIONS: {
				CREATE_ROLE: "CREATE_ROLE",
				GET_ALL_ROLE: "GET_ALL_ROLE",
				GET_ROLE: "GET_ROLE",
				UPDATE_ROLE: "UPDATE_ROLE",
				DELETE_ROLE: "DELETE_ROLE",
			},
			DESCRIPTIONS: {
				ROLE_CREATED: "Created new role",
				ROLE_UPDATED: "Updated role",
				ROLE_DELETED: "Deleted role",
				ROLE_RETRIEVED: "Retrieved role details",
				ROLES_RETRIEVED: "Retrieved role list",
			},
			PAGES: {
				ROLE_CREATION: "Role Creation",
				ROLE_UPDATE: "Role Update",
				ROLE_DELETION: "Role Deletion",
				ROLE_DETAILS: "Role Details",
				ROLE_LIST: "Role List",
			},
		},
		PERSON: {
			ACTIONS: {
				CREATE_PERSON: "CREATE_PERSON",
				GET_ALL_PERSON: "GET_ALL_PERSON",
				GET_PERSON: "GET_PERSON",
				UPDATE_PERSON: "UPDATE_PERSON",
				DELETE_PERSON: "DELETE_PERSON",
			},
			DESCRIPTIONS: {
				PERSON_CREATED: "Created new person",
				PERSON_UPDATED: "Updated person",
				PERSON_DELETED: "Deleted person",
				PERSON_RETRIEVED: "Retrieved person details",
				PERSONS_RETRIEVED: "Retrieved person list",
			},
			PAGES: {
				PERSON_CREATION: "Person Creation",
				PERSON_UPDATE: "Person Update",
				PERSON_DELETION: "Person Deletion",
				PERSON_DETAILS: "Person Details",
				PERSON_LIST: "Person List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			PERSON: "person",
			ROLE: "role",
			USER: "user",
			PRODUCT: "product",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			TRANSACTION: "transaction",
			LOCATION: "location",
			TRANSACTIONITEM: "transactionitem",
			STOCKRECORD: "stockrecord",
			DELIVERORDER: "deliverorder",
			ORGANIZATION: "organization",
			DELIVERYRECEIPT: "deliveryreceipt",
			DELIVERYREQUEST: "deliveryrequest",
			DELIVERYREQUESTITEM: "deliveryrequestitem",
			DELIVERYRECEIPTITEM: "deliveryreceiptitem",
			CATEGORY: "category",
			DELIVERY: "delivery",
			ITEM: "item",
			DELIVERYITEM: "deliveryitem",
			SUPPLIERITEM: "supplieritem",
			SUBCATEGORY: "subcategory",
			PRODUCTTYPE: "product_type",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			DELIVERYORDER: "deliveryorder",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			DELIVERYORDERITEM: "deliveryorderitem",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			PERSON: "person",
			ROLE: "role",
			PRODUCT: "product",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			TRANSACTION: "transaction",
			LOCATION: "location",
			TRANSACTIONITEM: "transactionitem",
			STOCKRECORD: "StockRecord",
			DELIVERORDER: "deliverorder",
			DELIVERYRECEIPT: "deliveryreceipt",
			DELIVERYREQUEST: "deliveryrequest",
			DELIVERYREQUESTITEM: "deliveryrequestitem",
			DELIVERYRECEIPTITEM: "deliveryreceiptitem",
			CATEGORY: "category",
			DELIVERY: "delivery",
			ITEM: "item",
			DELIVERYITEM: "deliveryitem",
			SUPPLIERITEM: "supplieritem",
			SUBCATEGORY: "subcategory",
			PRODUCTTYPE: "product_type",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			DELIVERYORDER: "delveryorder",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			DELIVERYORDERITEM: "deliveryorderitem",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
		},
		PERSON: {
			DESCRIPTIONS: {
				PERSON_CREATED: "Created new person",
				PERSON_UPDATED: "Updated person",
				PERSON_DELETED: "Deleted person",
			},
		},
		ROLE: {
			DESCRIPTIONS: {
				ROLE_CREATED: "Created new role",
				ROLE_UPDATED: "Updated role",
				ROLE_DELETED: "Deleted role",
			},
		},
		USER: {
			DESCRIPTIONS: {
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
			},
		},
		PRODUCT: {
			DESCRIPTIONS: {
				PRODUCT_CREATED: "Created new product",
				PRODUCT_UPDATED: "Updated product",
				PRODUCT_DELETED: "Deleted product",
			},
		},
		BATCH: {
			DESCRIPTIONS: {
				BATCH_CREATED: "Created new batch",
				BATCH_UPDATED: "Updated batch",
				BATCH_DELETED: "Deleted batch",
			},
		},
		STOCK: {
			DESCRIPTIONS: {
				STOCK_CREATED: "Created new stock",
				STOCK_UPDATED: "Updated stock",
				STOCK_DELETED: "Deleted stock",
			},
		},
		SUPPLIER: {
			DESCRIPTIONS: {
				SUPPLIER_CREATED: "Created new supplier",
				SUPPLIER_UPDATED: "Updated supplier",
				SUPPLIER_DELETED: "Deleted supplier",
			},
		},
		PURCHASEORDERITEM: {
			DESCRIPTIONS: {
				PURCHASEORDERITEM_CREATED: "Created new purchaseorderitem",
				PURCHASEORDERITEM_UPDATED: "Updated purchaseorderitem",
				PURCHASEORDERITEM_DELETED: "Deleted purchaseorderitem",
			},
		},
		TRANSACTION: {
			DESCRIPTIONS: {
				TRANSACTION_CREATED: "Created new transaction",
				TRANSACTION_UPDATED: "Updated transaction",
				TRANSACTION_DELETED: "Deleted transaction",
			},
		},
		LOCATION: {
			DESCRIPTIONS: {
				LOCATION_CREATED: "Created new location",
				LOCATION_UPDATED: "Updated location",
				LOCATION_DELETED: "Deleted location",
			},
		},
		TRANSACTIONITEM: {
			DESCRIPTIONS: {
				TRANSACTIONITEM_CREATED: "Created new transactionitem",
				TRANSACTIONITEM_UPDATED: "Updated transactionitem",
				TRANSACTIONITEM_DELETED: "Deleted transactionitem",
			},
		},
		STOCKRECORD: {
			DESCRIPTIONS: {
				STOCKRECORD_CREATED: "Stock record created",
				STOCKRECORD_UPDATED: "Stock record updated",
				STOCKRECORD_DELETED: "Stock record deleted",
			},
		},
		DELIVERORDER: {
			DESCRIPTIONS: {
				DELIVERORDER_CREATED: "Created new deliverorder",
				DELIVERORDER_UPDATED: "Updated deliverorder",
				DELIVERORDER_DELETED: "Deleted deliverorder",
			},
		},
		ORGANIZATION: {
			DESCRIPTIONS: {
				ORGANIZATION_CREATED: "Created new organization",
				ORGANIZATION_UPDATED: "Updated organization",
				ORGANIZATION_DELETED: "Deleted organization",
			},
		},
		DELIVERYRECEIPT: {
			DESCRIPTIONS: {
				DELIVERYRECEIPT_CREATED: "Created new deliveryreceipt",
				DELIVERYRECEIPT_UPDATED: "Updated deliveryreceipt",
				DELIVERYRECEIPT_DELETED: "Deleted deliveryreceipt",
			},
		},
		DELIVERYREQUEST: {
			DESCRIPTIONS: {
				DELIVERYREQUEST_CREATED: "Created new deliveryrequest",
				DELIVERYREQUEST_UPDATED: "Updated deliveryrequest",
				DELIVERYREQUEST_DELETED: "Deleted deliveryrequest",
			},
		},
		DELIVERYREQUESTITEM: {
			DESCRIPTIONS: {
				DELIVERYREQUESTITEM_CREATED: "Created new deliveryrequestitem",
				DELIVERYREQUESTITEM_UPDATED: "Updated deliveryrequestitem",
				DELIVERYREQUESTITEM_DELETED: "Deleted deliveryrequestitem",
			},
		},
		DELIVERYRECEIPTITEM: {
			DESCRIPTIONS: {
				DELIVERYRECEIPTITEM_CREATED: "Created new deliveryreceiptitem",
				DELIVERYRECEIPTITEM_UPDATED: "Updated deliveryreceiptitem",
				DELIVERYRECEIPTITEM_DELETED: "Deleted deliveryreceiptitem",
			},
		},
		CATEGORY: {
			DESCRIPTIONS: {
				CATEGORY_CREATED: "Created new category",
				CATEGORY_UPDATED: "Updated category",
				CATEGORY_DELETED: "Deleted category",
			},
		},
		DELIVERY: {
			DESCRIPTIONS: {
				DELIVERY_CREATED: "Created new delivery",
				DELIVERY_UPDATED: "Updated delivery",
				DELIVERY_DELETED: "Deleted delivery",
			},
		},
		ITEM: {
			DESCRIPTIONS: {
				ITEM_CREATED: "Created new item",
				ITEM_UPDATED: "Updated item",
				ITEM_DELETED: "Deleted item",
			},
		},
		DELIVERYITEM: {
			DESCRIPTIONS: {
				DELIVERYITEM_CREATED: "Created new deliveryitem",
				DELIVERYITEM_UPDATED: "Updated deliveryitem",
				DELIVERYITEM_DELETED: "Deleted deliveryitem",
			},
		},
		SUPPLIERITEM: {
			DESCRIPTIONS: {
				SUPPLIERITEM_CREATED: "Created new supplieritem",
				SUPPLIERITEM_UPDATED: "Updated supplieritem",
				SUPPLIERITEM_DELETED: "Deleted supplieritem",
			},
		},
		SUBCATEGORY: {
			DESCRIPTIONS: {
				SUBCATEGORY_CREATED: "Created new subcategory",
				SUBCATEGORY_UPDATED: "Updated subcategory",
				SUBCATEGORY_DELETED: "Deleted subcategory",
			},
		},
		PRODUCTTYPE: {
			DESCRIPTIONS: {
				PRODUCTTYPE_CREATED: "Product type created",
				PRODUCTTYPE_UPDATED: "Product type updated",
				PRODUCTTYPE_DELETED: "Product type deleted",
			},
		},
		ALERT: {
			DESCRIPTIONS: {
				ALERT_CREATED: "Created new alert",
				ALERT_UPDATED: "Updated alert",
				ALERT_DELETED: "Deleted alert",
			},
		},
		ACTIVITYLOG: {
			DESCRIPTIONS: {
				ACTIVITYLOG_CREATED: "Created new activitylog",
				ACTIVITYLOG_UPDATED: "Updated activitylog",
				ACTIVITYLOG_DELETED: "Deleted activitylog",
			},
		},
		AUDITLOG: {
			DESCRIPTIONS: {
				AUDITLOG_CREATED: "Created new auditlog",
				AUDITLOG_UPDATED: "Updated auditlog",
				AUDITLOG_DELETED: "Deleted auditlog",
			},
		},
		NOTIFICATION: {
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
			},
		},
		SYSTEMLOG: {
			DESCRIPTIONS: {
				SYSTEMLOG_CREATED: "Created new systemlog",
				SYSTEMLOG_UPDATED: "Updated systemlog",
				SYSTEMLOG_DELETED: "Deleted systemlog",
			},
		},
		DELIVERYORDER: {
			DESCRIPTIONS: {
				DELIVERYORDER_CREATED: "Created new deliveryorder",
				DELIVERYORDER_UPDATED: "Updated deliveryorder",
				DELIVERYORDER_DELETED: "Deleted deliveryorder",
			},
		},
		STOCKMOVEMENTITEM: {
			DESCRIPTIONS: {
				STOCKMOVEMENTITEM_CREATED: "Created new stockmovementitem",
				STOCKMOVEMENTITEM_UPDATED: "Updated stockmovementitem",
				STOCKMOVEMENTITEM_DELETED: "Deleted stockmovementitem",
			},
		},
		PRICE: {
			DESCRIPTIONS: {
				PRICE_CREATED: "Created new price",
				PRICE_UPDATED: "Updated price",
				PRICE_DELETED: "Deleted price",
			},
		},
		DELIVERYORDERITEM: {
			DESCRIPTIONS: {
				DELIVERYORDERITEM_CREATED: "Created new deliveryorderitem",
				DELIVERYORDERITEM_UPDATED: "Updated deliveryorderitem",
				DELIVERYORDERITEM_DELETED: "Deleted deliveryorderitem",
			},
		},
		METRICS: {
			DESCRIPTIONS: {
				METRICS_CREATED: "Created new metrics",
				METRICS_UPDATED: "Updated metrics",
				METRICS_DELETED: "Deleted metrics",
			},
		},
		PATIENT: {
			DESCRIPTIONS: {
				PATIENT_CREATED: "Created new patient",
				PATIENT_UPDATED: "Updated patient",
				PATIENT_DELETED: "Deleted patient",
			},
		},
		MEDICINE: {
			DESCRIPTIONS: {
				MEDICINE_CREATED: "Created new medicine",
				MEDICINE_UPDATED: "Updated medicine",
				MEDICINE_DELETED: "Deleted medicine",
			},
		},
		APPROVAL: {
			DESCRIPTIONS: {
				APPROVAL_CREATED: "Created new approval",
				APPROVAL_UPDATED: "Updated approval",
				APPROVAL_DELETED: "Deleted approval",
			},
		},

		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
	AUTH_CONFIG: {
		standard: "1d",
		persistent: undefined,
		temporary: "1h",
	} as const,
};

export type roles = "user" | "admin" | "viewer";
