export const config = {
	DEFAULT_UNKNOWN_USER_ID: "unknown",
	ERROR: {
		PERSON: {
			NOT_FOUND: "Person not found",
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update person",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
			GETTING_ALL_USERS: "Getting all persons",
		},
		USER: {
			NOT_FOUND: "User not found",
			INVALID_ID: "Invalid user ID",
			MISSING_ID: "Missing user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update user",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
			INVALID_USER_ID_FORMAT: "Invalid user ID format",
			INVALID_FIELDS_PARAMETER: "Invalid fields parameter",
			INVALID_QUERY_PARAMETERS: "Invalid query parameters",
			INVALID_UPDATE_DATA: "Invalid update data",
			REQUEST_BODY_EMPTY: "Request body cannot be empty",
			VALIDATION_FAILED: "Validation failed",
			FIRST_NAME_REQUIRED: "First name is required",
			LAST_NAME_REQUIRED: "Last name is required",
			UNAUTHORIZED_USER_ID_NOT_FOUND: "Unauthorized - User ID not found",
			ERROR_DURING_USER_CREATION: "Error during user creation",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
			UPLOADING_AVATAR: "Uploading avatar for user",
			AVATAR_UPLOADED: "Avatar uploaded successfully",
			ORGANIZATION_VERIFIED: "Organization verified",
			USER_ALREADY_EXISTS: "User already exists",

			INVALID_ID_FORMAT: "Invalid user ID format",

			CREATE_FAILED: "Error creating user",

			DELETE_FAILED: "Error deleting user",
			GET_FAILED: "Error getting user",
			GET_ALL_FAILED: "Error getting users",
			ERROR_GETTING: "Error getting user",
			ERROR_UPDATING: "Error updating user",
		},
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
		},
		TEMPLATE: {
			VALIDATION_FAILED: "Template validation failed",
			INVALID_ID_FORMAT: "Invalid template ID format",
			NOT_FOUND: "Template not found",
			CREATE_FAILED: "Error creating template",
			UPDATE_FAILED: "Error updating template",
			DELETE_FAILED: "Error deleting template",
			GET_FAILED: "Error getting template",
			GET_ALL_FAILED: "Error getting templates",
			ERROR_GETTING: "Error getting template",
			ERROR_UPDATING: "Error updating template",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		QUERY_PARAMS: {
			INVALID_ID: "Invalid ID",
			MISSING_ID: "ID parameter is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_PAGE: "Invalid page",
			INVALID_LIMIT: "Invalid limit",
			INVALID_ORDER: "Invalid order",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
			INVALID_SORT: "Invalid sort",
			SORT_MUST_BE_STRING: "Sort must be a string",
			INVALID_FILTER: "Invalid filter",
			FILTER_MUST_BE_STRING: "Filter must be a string",
			INVALID_QUERY: "Invalid query",
			QUERY_MUST_BE_STRING: "Query must be a string",
			INVALID_DOCUMENT: "Invalid document",
			DOCUMENT_MUST_BE_STRING: "Document must be a string",
			INVALID_PAGINATION: "Invalid pagination",
			PAGINATION_MUST_BE_STRING: "Pagination must be a string",
			INVALID_COUNT: "Invalid count",
			COUNT_MUST_BE_STRING: "Count must be a string",
			INVALID_GROUPBY: "Invalid groupBy",
			INVALID_COMBINATION: "Invalid combination",
		},
		COMMON: {
			SUPPLIER_ID: "Require Supplier Id or Source Id",
			INTERNAL_SERVER_ERROR: "Internal server error",
			VALIDATION_ERROR: "Validation error",
			NOT_FOUND: "Resource not found",
			UNAUTHORIZED: "Unauthorized access",
			NO_UPDATE_FIELDS: "No fields provided for update",
		},
		ROLE: {
			VALIDATION_FAILED: "Role validation failed",
			INVALID_ID_FORMAT: "Invalid role ID format",
			NOT_FOUND: "Role not found",
			CREATE_FAILED: "Error creating role",
			UPDATE_FAILED: "Error updating role",
			DELETE_FAILED: "Error deleting role",
			GET_FAILED: "Error getting role",
			GET_ALL_FAILED: "Error getting roles",
			ERROR_GETTING: "Error getting role",
			ERROR_UPDATING: "Error updating role",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},

		ORGANIZATION: {
			VALIDATION_FAILED: "Organization validation failed",
			INVALID_ID_FORMAT: "Invalid organization ID format",
			NOT_FOUND: "Organization not found",
			CREATE_FAILED: "Error creating organization",
			UPDATE_FAILED: "Error updating organization",
			DELETE_FAILED: "Error deleting organization",
			GET_FAILED: "Error getting organization",
			GET_ALL_FAILED: "Error getting organizations",
			ERROR_GETTING: "Error getting organization",
			ERROR_UPDATING: "Error updating organization",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		ACTIVITYLOG: {
			VALIDATION_FAILED: "ActivityLog validation failed",
			INVALID_ID_FORMAT: "Invalid activitylog ID format",
			NOT_FOUND: "ActivityLog not found",
			CREATE_FAILED: "Error creating activitylog",
			UPDATE_FAILED: "Error updating activitylog",
			DELETE_FAILED: "Error deleting activitylog",
			GET_FAILED: "Error getting activitylog",
			GET_ALL_FAILED: "Error getting activitylogs",
			ERROR_GETTING: "Error getting activitylog",
			ERROR_UPDATING: "Error updating activitylog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		AUDITLOG: {
			VALIDATION_FAILED: "AuditLog validation failed",
			INVALID_ID_FORMAT: "Invalid auditlog ID format",
			NOT_FOUND: "AuditLog not found",
			CREATE_FAILED: "Error creating auditlog",
			UPDATE_FAILED: "Error updating auditlog",
			DELETE_FAILED: "Error deleting auditlog",
			GET_FAILED: "Error getting auditlog",
			GET_ALL_FAILED: "Error getting auditlogs",
			ERROR_GETTING: "Error getting auditlog",
			ERROR_UPDATING: "Error updating auditlog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		NOTIFICATION: {
			VALIDATION_FAILED: "Notification validation failed",
			INVALID_ID_FORMAT: "Invalid notification ID format",
			NOT_FOUND: "Notification not found",
			CREATE_FAILED: "Error creating notification",
			UPDATE_FAILED: "Error updating notification",
			DELETE_FAILED: "Error deleting notification",
			GET_FAILED: "Error getting notification",
			GET_ALL_FAILED: "Error getting notifications",
			ERROR_GETTING: "Error getting notification",
			ERROR_UPDATING: "Error updating notification",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		SYSTEMLOG: {
			VALIDATION_FAILED: "SystemLog validation failed",
			INVALID_ID_FORMAT: "Invalid systemlog ID format",
			NOT_FOUND: "SystemLog not found",
			CREATE_FAILED: "Error creating systemlog",
			UPDATE_FAILED: "Error updating systemlog",
			DELETE_FAILED: "Error deleting systemlog",
			GET_FAILED: "Error getting systemlog",
			GET_ALL_FAILED: "Error getting systemlogs",
			ERROR_GETTING: "Error getting systemlog",
			ERROR_UPDATING: "Error updating systemlog",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
		METRICS: {
			VALIDATION_FAILED: "Metrics validation failed",
			INVALID_ID_FORMAT: "Invalid metrics ID format",
			NOT_FOUND: "Metrics not found",
			CREATE_FAILED: "Error creating metrics",
			UPDATE_FAILED: "Error updating metrics",
			DELETE_FAILED: "Error deleting metrics",
			GET_FAILED: "Error getting metrics",
			GET_ALL_FAILED: "Error getting metrics",
			ERROR_GETTING: "Error getting metrics",
			ERROR_UPDATING: "Error updating metrics",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be asc or desc",
		},
	},
	INFO: {
		USER: {
			REGISTERING_USER: "Registering user with email:",
			CREATING_USER_WITH_PERSON_ID: "Creating user with personId:",
			LOGGING_IN_USER: "Logging in user with email:",
		},
	},
	SUCCESS: {
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
		},
		TEMPLATE: {
			CREATED: "Template created successfully",
			UPDATED: "Template updated successfully",
			DELETED: "Template deleted successfully",
			RETRIEVED: "Template retrieved successfully",
			RETRIEVED_ALL: "Templates retrieved successfully",
			GETTING_BY_ID: "Getting template by ID",
		},
		COMMON: {
			OPERATION_SUCCESSFUL: "Operation completed successfully",
		},
		PERSON: {
			SOFT_DELETING: "Soft deleting user",
			CREATED: "Person created successfully",
			UPDATED: "Person updated successfully",
			DELETED: "Person deleted successfully",
			RETRIEVED: "Person retrieved successfully",
			RETRIEVED_ALL: "Persons retrieved successfully",
			GETTING_BY_ID: "Getting person by ID",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		ROLE: {
			CREATED: "Role created successfully",
			UPDATED: "Role updated successfully",
			DELETED: "Role deleted successfully",
			RETRIEVED: "Role retrieved successfully",
			RETRIEVED_ALL: "Roles retrieved successfully",
			GETTING_BY_ID: "Getting role by ID",
		},
		USER: {
			CREATED: "User created successfully",
			UPDATED: "User updated successfully",
			DELETED: "User deleted successfully",
			RETRIEVED: "User retrieved successfully",
			RETRIEVED_ALL: "Users retrieved successfully",
			GETTING_BY_ID: "Getting user by ID",
		},
		ORGANIZATION: {
			CREATED: "Organization created successfully",
			UPDATED: "Organization updated successfully",
			DELETED: "Organization deleted successfully",
			RETRIEVED: "Organization retrieved successfully",
			RETRIEVED_ALL: "Organizations retrieved successfully",
			GETTING_BY_ID: "Getting organization by ID",
		},
		
		ACTIVITYLOG: {
			CREATED: "ActivityLog created successfully",
			UPDATED: "ActivityLog updated successfully",
			DELETED: "ActivityLog deleted successfully",
			RETRIEVED: "ActivityLog retrieved successfully",
			RETRIEVED_ALL: "ActivityLogs retrieved successfully",
			GETTING_BY_ID: "Getting activitylog by ID",
		},
		AUDITLOG: {
			CREATED: "AuditLog created successfully",
			UPDATED: "AuditLog updated successfully",
			DELETED: "AuditLog deleted successfully",
			RETRIEVED: "AuditLog retrieved successfully",
			RETRIEVED_ALL: "AuditLogs retrieved successfully",
			GETTING_BY_ID: "Getting auditlog by ID",
		},
		NOTIFICATION: {
			CREATED: "Notification created successfully",
			UPDATED: "Notification updated successfully",
			DELETED: "Notification deleted successfully",
			RETRIEVED: "Notification retrieved successfully",
			RETRIEVED_ALL: "Notifications retrieved successfully",
			GETTING_BY_ID: "Getting notification by ID",
		},
		SYSTEMLOG: {
			CREATED: "SystemLog created successfully",
			UPDATED: "SystemLog updated successfully",
			DELETED: "SystemLog deleted successfully",
			RETRIEVED: "SystemLog retrieved successfully",
			RETRIEVED_ALL: "SystemLogs retrieved successfully",
			GETTING_BY_ID: "Getting systemlog by ID",
		},
	},

	ACTIVITY_LOG: {
		ORGANIZATION: {
			ACTIONS: {
				CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
				GET_ALL_ORGANIZATIONS: "GET_ALL_ORGANIZATIONS",
				GET_ORGANIZATION: "GET_ORGANIZATION",
				UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
				DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
			},
			DESCRIPTIONS: {
				ORGANIZATION_CREATED: "Created new organization",
				ORGANIZATION_UPDATED: "Updated organization",
				ORGANIZATION_DELETED: "Deleted organization",
				ORGANIZATION_RETRIEVED: "Retrieved organization details",
				ORGANIZATIONS_RETRIEVED: "Retrieved organizations list",
			},
			PAGES: {
				ORGANIZATION_CREATION: "Organization Creation",
				ORGANIZATION_UPDATE: "Organization Update",
				ORGANIZATION_DELETION: "Organization Deletion",
				ORGANIZATION_DETAILS: "Organization Details",
				ORGANIZATIONS_LIST: "Organizations List",
			},
		},
		METRICS: {
			ACTIONS: {
				CREATE_METRICS: "CREATE_METRICS",
				GET_ALL_METRICS: "GET_ALL_METRICS",
				GET_METRICS: "GET_METRICS",
				UPDATE_METRICS: "UPDATE_METRICS",
				DELETE_METRICS: "DELETE_METRICS",
			},
			DESCRIPTIONS: {
				METRICS_CREATED: "Created new metrics",
				METRICS_UPDATED: "Updated metrics",
				METRICS_DELETED: "Deleted metrics",
				METRICS_RETRIEVED: "Retrieved metrics details",
				METRICSS_RETRIEVED: "Retrieved metrics list",
			},
			PAGES: {
				METRICS_CREATION: "Metrics Creation",
				METRICS_UPDATE: "Metrics Update",
				METRICS_DELETION: "Metrics Deletion",
				METRICS_DETAILS: "Metrics Details",
				METRICS_LIST: "Metrics List",
			},
		},
		SYSTEMLOG: {
			ACTIONS: {
				CREATE_SYSTEMLOG: "CREATE_SYSTEMLOG",
				GET_ALL_SYSTEMLOG: "GET_ALL_SYSTEMLOG",
				GET_SYSTEMLOG: "GET_SYSTEMLOG",
				UPDATE_SYSTEMLOG: "UPDATE_SYSTEMLOG",
				DELETE_SYSTEMLOG: "DELETE_SYSTEMLOG",
			},
			DESCRIPTIONS: {
				SYSTEMLOG_CREATED: "Created new systemlog",
				SYSTEMLOG_UPDATED: "Updated systemlog",
				SYSTEMLOG_DELETED: "Deleted systemlog",
				SYSTEMLOG_RETRIEVED: "Retrieved systemlog details",
				SYSTEMLOGS_RETRIEVED: "Retrieved systemlog list",
			},
			PAGES: {
				SYSTEMLOG_CREATION: "SystemLog Creation",
				SYSTEMLOG_UPDATE: "SystemLog Update",
				SYSTEMLOG_DELETION: "SystemLog Deletion",
				SYSTEMLOG_DETAILS: "SystemLog Details",
				SYSTEMLOG_LIST: "SystemLog List",
			},
		},
		NOTIFICATION: {
			ACTIONS: {
				CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
				GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",
				GET_NOTIFICATION: "GET_NOTIFICATION",
				UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
				DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
			},
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
				NOTIFICATION_RETRIEVED: "Retrieved notification details",
				NOTIFICATIONS_RETRIEVED: "Retrieved notification list",
			},
			PAGES: {
				NOTIFICATION_CREATION: "Notification Creation",
				NOTIFICATION_UPDATE: "Notification Update",
				NOTIFICATION_DELETION: "Notification Deletion",
				NOTIFICATION_DETAILS: "Notification Details",
				NOTIFICATION_LIST: "Notification List",
			},
		},
		AUDITLOG: {
			ACTIONS: {
				CREATE_AUDITLOG: "CREATE_AUDITLOG",
				GET_ALL_AUDITLOG: "GET_ALL_AUDITLOG",
				GET_AUDITLOG: "GET_AUDITLOG",
				UPDATE_AUDITLOG: "UPDATE_AUDITLOG",
				DELETE_AUDITLOG: "DELETE_AUDITLOG",
			},
			DESCRIPTIONS: {
				AUDITLOG_CREATED: "Created new auditlog",
				AUDITLOG_UPDATED: "Updated auditlog",
				AUDITLOG_DELETED: "Deleted auditlog",
				AUDITLOG_RETRIEVED: "Retrieved auditlog details",
				AUDITLOGS_RETRIEVED: "Retrieved auditlog list",
			},
			PAGES: {
				AUDITLOG_CREATION: "AuditLog Creation",
				AUDITLOG_UPDATE: "AuditLog Update",
				AUDITLOG_DELETION: "AuditLog Deletion",
				AUDITLOG_DETAILS: "AuditLog Details",
				AUDITLOG_LIST: "AuditLog List",
			},
		},
		ACTIVITYLOG: {
			ACTIONS: {
				CREATE_ACTIVITYLOG: "CREATE_ACTIVITYLOG",
				GET_ALL_ACTIVITYLOG: "GET_ALL_ACTIVITYLOG",
				GET_ACTIVITYLOG: "GET_ACTIVITYLOG",
				UPDATE_ACTIVITYLOG: "UPDATE_ACTIVITYLOG",
				DELETE_ACTIVITYLOG: "DELETE_ACTIVITYLOG",
			},
			DESCRIPTIONS: {
				ACTIVITYLOG_CREATED: "Created new activitylog",
				ACTIVITYLOG_UPDATED: "Updated activitylog",
				ACTIVITYLOG_DELETED: "Deleted activitylog",
				ACTIVITYLOG_RETRIEVED: "Retrieved activitylog details",
				ACTIVITYLOGS_RETRIEVED: "Retrieved activitylog list",
			},
			PAGES: {
				ACTIVITYLOG_CREATION: "ActivityLog Creation",
				ACTIVITYLOG_UPDATE: "ActivityLog Update",
				ACTIVITYLOG_DELETION: "ActivityLog Deletion",
				ACTIVITYLOG_DETAILS: "ActivityLog Details",
				ACTIVITYLOG_LIST: "ActivityLog List",
			},
		},
		ROLE: {
			ACTIONS: {
				CREATE_ROLE: "CREATE_ROLE",
				GET_ALL_ROLE: "GET_ALL_ROLE",
				GET_ROLE: "GET_ROLE",
				UPDATE_ROLE: "UPDATE_ROLE",
				DELETE_ROLE: "DELETE_ROLE",
			},
			DESCRIPTIONS: {
				ROLE_CREATED: "Created new role",
				ROLE_UPDATED: "Updated role",
				ROLE_DELETED: "Deleted role",
				ROLE_RETRIEVED: "Retrieved role details",
				ROLES_RETRIEVED: "Retrieved role list",
			},
			PAGES: {
				ROLE_CREATION: "Role Creation",
				ROLE_UPDATE: "Role Update",
				ROLE_DELETION: "Role Deletion",
				ROLE_DETAILS: "Role Details",
				ROLE_LIST: "Role List",
			},
		},
		PERSON: {
			ACTIONS: {
				CREATE_PERSON: "CREATE_PERSON",
				GET_ALL_PERSON: "GET_ALL_PERSON",
				GET_PERSON: "GET_PERSON",
				UPDATE_PERSON: "UPDATE_PERSON",
				DELETE_PERSON: "DELETE_PERSON",
			},
			DESCRIPTIONS: {
				PERSON_CREATED: "Created new person",
				PERSON_UPDATED: "Updated person",
				PERSON_DELETED: "Deleted person",
				PERSON_RETRIEVED: "Retrieved person details",
				PERSONS_RETRIEVED: "Retrieved person list",
			},
			PAGES: {
				PERSON_CREATION: "Person Creation",
				PERSON_UPDATE: "Person Update",
				PERSON_DELETION: "Person Deletion",
				PERSON_DETAILS: "Person Details",
				PERSON_LIST: "Person List",
			},
		},
		TEMPLATE: {
			ACTIONS: {
				CREATE_TEMPLATE: "CREATE_TEMPLATE",
				GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
				GET_TEMPLATE: "GET_TEMPLATE",
				UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
				DELETE_TEMPLATE: "DELETE_TEMPLATE",
				USER_LOGIN: "USER_LOGIN",
				USER_LOGOUT: "USER_LOGOUT",
				USER_REGISTRATION: "USER_REGISTRATION",
				PASSWORD_UPDATE: "PASSWORD_UPDATE",
			},
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				TEMPLATE_RETRIEVED: "Retrieved template details",
				TEMPLATES_RETRIEVED: "Retrieved template list",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
				USER_REGISTERED: "User registered",
				PASSWORD_CHANGED: "Password changed",
			},
			PAGES: {
				TEMPLATE_CREATION: "Template Creation",
				TEMPLATE_UPDATE: "Template Update",
				TEMPLATE_DELETION: "Template Deletion",
				TEMPLATE_DETAILS: "Template Details",
				TEMPLATE_LIST: "Template List",
				USER_LOGIN: "User Login",
				USER_REGISTRATION: "User Registration",
				PASSWORD_CHANGE: "Password Change",
			},
		},
	},

	AUDIT_LOG: {
		ACTIONS: {
			CREATE: "CREATE",
			READ: "READ",
			UPDATE: "UPDATE",
			DELETE: "DELETE",
			LOGIN: "LOGIN",
			LOGOUT: "LOGOUT",
			REGISTER: "REGISTER",
		},
		RESOURCES: {
			TEMPLATE: "templates",
			USERS: "users",
			ORGANIZATIONS: "organizations",
			AUTH: "auth",
			PERSON: "person",
			ROLE: "role",
			USER: "user",
			PRODUCT: "product",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			TRANSACTION: "transaction",
			LOCATION: "location",
			TRANSACTIONITEM: "transactionitem",
			STOCKRECORD: "stockrecord",
			DELIVERORDER: "deliverorder",
			ORGANIZATION: "organization",
			DELIVERYRECEIPT: "deliveryreceipt",
			DELIVERYREQUEST: "deliveryrequest",
			DELIVERYREQUESTITEM: "deliveryrequestitem",
			DELIVERYRECEIPTITEM: "deliveryreceiptitem",
			CATEGORY: "category",
			DELIVERY: "delivery",
			ITEM: "item",
			DELIVERYITEM: "deliveryitem",
			SUPPLIERITEM: "supplieritem",
			SUBCATEGORY: "subcategory",
			PRODUCTTYPE: "product_type",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			DELIVERYORDER: "deliveryorder",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			DELIVERYORDERITEM: "deliveryorderitem",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
		},
		SEVERITY: {
			LOW: "LOW" as const,
			MEDIUM: "MEDIUM" as const,
			HIGH: "HIGH" as const,
			CRITICAL: "CRITICAL" as const,
		},
		ENTITY_TYPES: {
			TEMPLATE: "template",
			USER: "user",
			ORGANIZATION: "organization",
			PERSON: "person",
			ROLE: "role",
			PRODUCT: "product",
			BATCH: "batch",
			STOCK: "stock",
			SUPPLIER: "supplier",
			PURCHASEORDERITEM: "purchaseorderitem",
			TRANSACTION: "transaction",
			LOCATION: "location",
			TRANSACTIONITEM: "transactionitem",
			STOCKRECORD: "StockRecord",
			DELIVERORDER: "deliverorder",
			DELIVERYRECEIPT: "deliveryreceipt",
			DELIVERYREQUEST: "deliveryrequest",
			DELIVERYREQUESTITEM: "deliveryrequestitem",
			DELIVERYRECEIPTITEM: "deliveryreceiptitem",
			CATEGORY: "category",
			DELIVERY: "delivery",
			ITEM: "item",
			DELIVERYITEM: "deliveryitem",
			SUPPLIERITEM: "supplieritem",
			SUBCATEGORY: "subcategory",
			PRODUCTTYPE: "product_type",
			ALERT: "alert",
			ACTIVITYLOG: "activitylog",
			AUDITLOG: "auditlog",
			NOTIFICATION: "notification",
			SYSTEMLOG: "systemlog",
			DELIVERYORDER: "delveryorder",
			STOCKMOVEMENTITEM: "stockmovementitem",
			PRICE: "price",
			DELIVERYORDERITEM: "deliveryorderitem",
			METRICS: "metrics",
			PATIENT: "patient",
			MEDICINE: "medicine",
			APPROVAL: "approval",
		},
		PERSON: {
			DESCRIPTIONS: {
				PERSON_CREATED: "Created new person",
				PERSON_UPDATED: "Updated person",
				PERSON_DELETED: "Deleted person",
			},
		},
		ROLE: {
			DESCRIPTIONS: {
				ROLE_CREATED: "Created new role",
				ROLE_UPDATED: "Updated role",
				ROLE_DELETED: "Deleted role",
			},
		},
		USER: {
			DESCRIPTIONS: {
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
			},
		},
		PRODUCT: {
			DESCRIPTIONS: {
				PRODUCT_CREATED: "Created new product",
				PRODUCT_UPDATED: "Updated product",
				PRODUCT_DELETED: "Deleted product",
			},
		},
		BATCH: {
			DESCRIPTIONS: {
				BATCH_CREATED: "Created new batch",
				BATCH_UPDATED: "Updated batch",
				BATCH_DELETED: "Deleted batch",
			},
		},
		STOCK: {
			DESCRIPTIONS: {
				STOCK_CREATED: "Created new stock",
				STOCK_UPDATED: "Updated stock",
				STOCK_DELETED: "Deleted stock",
			},
		},
		SUPPLIER: {
			DESCRIPTIONS: {
				SUPPLIER_CREATED: "Created new supplier",
				SUPPLIER_UPDATED: "Updated supplier",
				SUPPLIER_DELETED: "Deleted supplier",
			},
		},
		PURCHASEORDERITEM: {
			DESCRIPTIONS: {
				PURCHASEORDERITEM_CREATED: "Created new purchaseorderitem",
				PURCHASEORDERITEM_UPDATED: "Updated purchaseorderitem",
				PURCHASEORDERITEM_DELETED: "Deleted purchaseorderitem",
			},
		},
		TRANSACTION: {
			DESCRIPTIONS: {
				TRANSACTION_CREATED: "Created new transaction",
				TRANSACTION_UPDATED: "Updated transaction",
				TRANSACTION_DELETED: "Deleted transaction",
			},
		},
		LOCATION: {
			DESCRIPTIONS: {
				LOCATION_CREATED: "Created new location",
				LOCATION_UPDATED: "Updated location",
				LOCATION_DELETED: "Deleted location",
			},
		},
		TRANSACTIONITEM: {
			DESCRIPTIONS: {
				TRANSACTIONITEM_CREATED: "Created new transactionitem",
				TRANSACTIONITEM_UPDATED: "Updated transactionitem",
				TRANSACTIONITEM_DELETED: "Deleted transactionitem",
			},
		},
		STOCKRECORD: {
			DESCRIPTIONS: {
				STOCKRECORD_CREATED: "Stock record created",
				STOCKRECORD_UPDATED: "Stock record updated",
				STOCKRECORD_DELETED: "Stock record deleted",
			},
		},
		DELIVERORDER: {
			DESCRIPTIONS: {
				DELIVERORDER_CREATED: "Created new deliverorder",
				DELIVERORDER_UPDATED: "Updated deliverorder",
				DELIVERORDER_DELETED: "Deleted deliverorder",
			},
		},
		ORGANIZATION: {
			DESCRIPTIONS: {
				ORGANIZATION_CREATED: "Created new organization",
				ORGANIZATION_UPDATED: "Updated organization",
				ORGANIZATION_DELETED: "Deleted organization",
			},
		},
		DELIVERYRECEIPT: {
			DESCRIPTIONS: {
				DELIVERYRECEIPT_CREATED: "Created new deliveryreceipt",
				DELIVERYRECEIPT_UPDATED: "Updated deliveryreceipt",
				DELIVERYRECEIPT_DELETED: "Deleted deliveryreceipt",
			},
		},
		DELIVERYREQUEST: {
			DESCRIPTIONS: {
				DELIVERYREQUEST_CREATED: "Created new deliveryrequest",
				DELIVERYREQUEST_UPDATED: "Updated deliveryrequest",
				DELIVERYREQUEST_DELETED: "Deleted deliveryrequest",
			},
		},
		DELIVERYREQUESTITEM: {
			DESCRIPTIONS: {
				DELIVERYREQUESTITEM_CREATED: "Created new deliveryrequestitem",
				DELIVERYREQUESTITEM_UPDATED: "Updated deliveryrequestitem",
				DELIVERYREQUESTITEM_DELETED: "Deleted deliveryrequestitem",
			},
		},
		DELIVERYRECEIPTITEM: {
			DESCRIPTIONS: {
				DELIVERYRECEIPTITEM_CREATED: "Created new deliveryreceiptitem",
				DELIVERYRECEIPTITEM_UPDATED: "Updated deliveryreceiptitem",
				DELIVERYRECEIPTITEM_DELETED: "Deleted deliveryreceiptitem",
			},
		},
		CATEGORY: {
			DESCRIPTIONS: {
				CATEGORY_CREATED: "Created new category",
				CATEGORY_UPDATED: "Updated category",
				CATEGORY_DELETED: "Deleted category",
			},
		},
		DELIVERY: {
			DESCRIPTIONS: {
				DELIVERY_CREATED: "Created new delivery",
				DELIVERY_UPDATED: "Updated delivery",
				DELIVERY_DELETED: "Deleted delivery",
			},
		},
		ITEM: {
			DESCRIPTIONS: {
				ITEM_CREATED: "Created new item",
				ITEM_UPDATED: "Updated item",
				ITEM_DELETED: "Deleted item",
			},
		},
		DELIVERYITEM: {
			DESCRIPTIONS: {
				DELIVERYITEM_CREATED: "Created new deliveryitem",
				DELIVERYITEM_UPDATED: "Updated deliveryitem",
				DELIVERYITEM_DELETED: "Deleted deliveryitem",
			},
		},
		SUPPLIERITEM: {
			DESCRIPTIONS: {
				SUPPLIERITEM_CREATED: "Created new supplieritem",
				SUPPLIERITEM_UPDATED: "Updated supplieritem",
				SUPPLIERITEM_DELETED: "Deleted supplieritem",
			},
		},
		SUBCATEGORY: {
			DESCRIPTIONS: {
				SUBCATEGORY_CREATED: "Created new subcategory",
				SUBCATEGORY_UPDATED: "Updated subcategory",
				SUBCATEGORY_DELETED: "Deleted subcategory",
			},
		},
		PRODUCTTYPE: {
			DESCRIPTIONS: {
				PRODUCTTYPE_CREATED: "Product type created",
				PRODUCTTYPE_UPDATED: "Product type updated",
				PRODUCTTYPE_DELETED: "Product type deleted",
			},
		},
		ALERT: {
			DESCRIPTIONS: {
				ALERT_CREATED: "Created new alert",
				ALERT_UPDATED: "Updated alert",
				ALERT_DELETED: "Deleted alert",
			},
		},
		ACTIVITYLOG: {
			DESCRIPTIONS: {
				ACTIVITYLOG_CREATED: "Created new activitylog",
				ACTIVITYLOG_UPDATED: "Updated activitylog",
				ACTIVITYLOG_DELETED: "Deleted activitylog",
			},
		},
		AUDITLOG: {
			DESCRIPTIONS: {
				AUDITLOG_CREATED: "Created new auditlog",
				AUDITLOG_UPDATED: "Updated auditlog",
				AUDITLOG_DELETED: "Deleted auditlog",
			},
		},
		NOTIFICATION: {
			DESCRIPTIONS: {
				NOTIFICATION_CREATED: "Created new notification",
				NOTIFICATION_UPDATED: "Updated notification",
				NOTIFICATION_DELETED: "Deleted notification",
			},
		},
		SYSTEMLOG: {
			DESCRIPTIONS: {
				SYSTEMLOG_CREATED: "Created new systemlog",
				SYSTEMLOG_UPDATED: "Updated systemlog",
				SYSTEMLOG_DELETED: "Deleted systemlog",
			},
		},
		DELIVERYORDER: {
			DESCRIPTIONS: {
				DELIVERYORDER_CREATED: "Created new deliveryorder",
				DELIVERYORDER_UPDATED: "Updated deliveryorder",
				DELIVERYORDER_DELETED: "Deleted deliveryorder",
			},
		},
		STOCKMOVEMENTITEM: {
			DESCRIPTIONS: {
				STOCKMOVEMENTITEM_CREATED: "Created new stockmovementitem",
				STOCKMOVEMENTITEM_UPDATED: "Updated stockmovementitem",
				STOCKMOVEMENTITEM_DELETED: "Deleted stockmovementitem",
			},
		},
		PRICE: {
			DESCRIPTIONS: {
				PRICE_CREATED: "Created new price",
				PRICE_UPDATED: "Updated price",
				PRICE_DELETED: "Deleted price",
			},
		},
		DELIVERYORDERITEM: {
			DESCRIPTIONS: {
				DELIVERYORDERITEM_CREATED: "Created new deliveryorderitem",
				DELIVERYORDERITEM_UPDATED: "Updated deliveryorderitem",
				DELIVERYORDERITEM_DELETED: "Deleted deliveryorderitem",
			},
		},
		METRICS: {
			DESCRIPTIONS: {
				METRICS_CREATED: "Created new metrics",
				METRICS_UPDATED: "Updated metrics",
				METRICS_DELETED: "Deleted metrics",
			},
		},
		PATIENT: {
			DESCRIPTIONS: {
				PATIENT_CREATED: "Created new patient",
				PATIENT_UPDATED: "Updated patient",
				PATIENT_DELETED: "Deleted patient",
			},
		},
		MEDICINE: {
			DESCRIPTIONS: {
				MEDICINE_CREATED: "Created new medicine",
				MEDICINE_UPDATED: "Updated medicine",
				MEDICINE_DELETED: "Deleted medicine",
			},
		},
		APPROVAL: {
			DESCRIPTIONS: {
				APPROVAL_CREATED: "Created new approval",
				APPROVAL_UPDATED: "Updated approval",
				APPROVAL_DELETED: "Deleted approval",
			},
		},

		TEMPLATE: {
			DESCRIPTIONS: {
				TEMPLATE_CREATED: "Created new template",
				TEMPLATE_UPDATED: "Updated template",
				TEMPLATE_DELETED: "Deleted template",
				USER_CREATED: "Created new user",
				USER_UPDATED: "Updated user",
				USER_DELETED: "Deleted user",
				USER_LOGGED_IN: "User logged in",
				USER_LOGGED_OUT: "User logged out",
			},
		},
	},
	AUTH_CONFIG: {
		standard: "1d",
		persistent: undefined,
		temporary: "1h",
	} as const,
};

export type roles = "user" | "admin" | "viewer";
